/* eslint-disable react/no-unescaped-entities */
import type { Metadata } from "next";
import Link from "next/link";
import { SourceList } from "@/components/SourceList";

export const metadata: Metadata = { title: "The War in Five Minutes", description: "The causes, course, peace, and consequences of the War of 1812 in one concise visual narrative." };

export default function FiveMinutes() {
  return (
    <main id="main" className="page-shell five-minute-page">
      <header className="page-title"><p className="section-kicker">Tell me the war in…</p><h1>Five minutes</h1><p>A young republic, a global war, three invasions of Canada, an ocean it could not control, a capital burned, a city held, a treaty signed, and a battle fought before the news arrived.</p><div className="reading-meta"><span>≈ 1,600 words</span><span>1803–1818</span></div></header>
      <article className="longread">
        <section><span className="big-number">01</span><h2>A global war traps a neutral republic</h2><p>The War of 1812 grew inside a much larger struggle. Britain and Napoleonic France were at war for mastery of Europe and the Atlantic. The United States wanted to trade with both. Neither belligerent was willing to let neutral commerce help the other.</p><p>Britain's Royal Navy stopped American vessels, enforced trade restrictions, and impressed sailors it claimed were British subjects or deserters. Americans insisted that a sailor protected by American papers and sailing under the American flag could not simply be taken. Documentary identity at sea was messy, and British need for manpower was enormous. The result was an issue that combined individual coercion, national honor, and the basic question of whether American sovereignty meant anything on the ocean.</p><p>At the same time, American settlement pushed into Indigenous homelands. Tecumseh and Tenskwatawa sought a coalition strong enough to resist further land cessions. British officials saw Native allies as a barrier protecting Canada; Native leaders saw British support as a possible means of preserving political and territorial autonomy. The alliance was real. Its purposes were not identical.</p></section>
        <section><span className="big-number">02</span><h2>The United States chooses war—and divides over it</h2><p>President James Madison asked Congress for war in June 1812, citing maritime coercion, violations of American waters and commerce, and British support for Indigenous resistance. War Hawks also imagined pressure on—or conquest of—British North America. Congress approved by sharply divided votes. New England Federalists and other opponents believed war would destroy commerce and expose a militarily unprepared country.</p><p>They were correct about the lack of preparation. The regular army was small, finance weak, logistics primitive, militia obligations contested, and command fractured. They were also part of a political opposition that sometimes crossed into obstruction and, in Baltimore, into bloodshed. Days after the declaration, a pro-war mob destroyed the office of the antiwar <em>Federal Republican</em>. In July another mob invaded the city jail and murdered Revolutionary War General James M. Lingan while brutally attacking Henry “Light-Horse Harry” Lee, Alexander Contee Hanson, and others.</p></section>
        <section><span className="big-number">03</span><h2>The invasion of Canada fails</h2><p>American strategy treated Canada as Britain's vulnerable point. Instead, the first campaigns exposed the distance between maps and movement. William Hull's army crossed from Detroit into Upper Canada, lost confidence, and withdrew. Isaac Brock and Tecumseh used audacity, intelligence, and deception to make their smaller force appear overwhelming. Hull surrendered Detroit without enduring an assault.</p><p>At Queenston Heights, American troops crossed the Niagara and gained ground, but militia on the American bank refused to follow. British, Canadian, and Indigenous forces retook the heights. Brock was killed and became a hero of later Canadian memory. The campaigns preserved Upper Canada and confirmed that its defenders were not one thing: British regulars, colonial militia, Black militia members, and Native nations fought in overlapping but distinct causes.</p></section>
        <section><span className="big-number">04</span><h2>Small victories at sea; a vast war on the lakes</h2><p>The Royal Navy dominated the Atlantic, yet American frigates won spectacular single-ship actions. USS <em>Constitution</em> defeated HMS <em>Guerriere</em>; USS <em>United States</em> captured HMS <em>Macedonian</em>; <em>Constitution</em> defeated HMS <em>Java</em>. These victories did not control the ocean, but they proved American ships could be formidable and gave a discouraged public heroes, trophies, and the name “Old Ironsides.” Black sailors served in American naval and privateering crews, complicating the patriotic language of a slaveholding republic.</p><p>On the Great Lakes, navies had to be built almost from nothing. Shipyards at Sackets Harbor, Kingston, Erie, and elsewhere turned forests, transported cannon, specialized labor, and distant supply lines into fleets. Whoever controlled the water controlled the movement of armies. Oliver Hazard Perry's victory on Lake Erie forced the British evacuation of Detroit; William Henry Harrison followed and defeated the retreating force at the Thames, where Tecumseh was killed. His death gravely weakened the Indigenous coalition resisting American expansion.</p><p>The war also crossed Cape Horn. USS <em>Essex</em> attacked British whaling in the Pacific, seized prizes, intervened in Marquesan politics, and was finally defeated by HMS <em>Phoebe</em> and HMS <em>Cherub</em> near Valparaíso. The Pacific campaign changed no border. It reveals how misleading the usual small map of this war can be.</p></section>
        <section><span className="big-number">05</span><h2>The conflict reaches homes—and the economy</h2><p>In 1813, forces occupied and burned towns around York and the Niagara frontier. British raids struck Chesapeake communities. Occupation meant requisitioned food, destroyed mills, missing animals, displaced families, suspicion, and choices made under threat. Enslaved people watched British ships as possible routes out of bondage. Escape could offer freedom while risking separation, recapture, and an unknown future.</p><p>The Royal Navy tightened its blockade. American privateers captured merchant ships and imposed costs, but they could not reopen the coast. Insurance rose, vessels remained in port, customs revenue collapsed, imported goods grew scarce, and federal credit weakened. The blockade also made the Chesapeake an operating base from which British commanders gathered intelligence and prepared larger attacks.</p><p>Farther south, the Anglo-American war overlapped with a Muscogee civil war, Spanish authority in Florida, and American expansion. Red Stick resistance fought other Muscogee factions as well as American, Cherokee, and allied forces. Andrew Jackson's victory at Horseshoe Bend led to the Treaty of Fort Jackson, which imposed a huge land cession—including land belonging to Native communities that had fought beside the United States.</p></section>
        <section><span className="big-number">06</span><h2>In 1814, everything becomes more dangerous</h2><p>Napoleon's first abdication freed British troops and attention for North America. The United States had learned too: American regulars fought effectively at Chippawa, Lundy's Lane, and Fort Erie. Better battlefield performance did not create strategic decision. The Niagara campaign consumed lives and ended near the line where it began.</p><p>A much larger British invasion moved south along Lake Champlain. At Plattsburgh on September 11, Thomas Macdonough arranged his squadron so damaged ships could rotate and bring fresh guns into action. The British squadron surrendered. Without control of the lake, Governor General George Prévost withdrew his army. The failure mattered at Ghent because an army that could not advance supplied no territory to bargain with.</p><p>In the Chesapeake, British troops landed at Benedict, defeated an improvised American defense at Bladensburg, and entered Washington. They burned the Capitol, President's House, and public buildings; Americans destroyed the Navy Yard to deny it to them. The famous Dolley Madison story is real at its core but incomplete without the enslaved and free workers who moved property and information through the crisis. Meanwhile, enslaved people reached British forces under a proclamation offering reception, military service, or resettlement. British policy aimed to damage the United States. Freedom seekers used that policy to act for themselves.</p></section>
        <section className="baltimore-five"><span className="big-number">07</span><h2>Baltimore holds</h2><p>Baltimore had spent two years preparing. Samuel Smith oversaw earthworks, militia, regulars, artillery, sailors, harbor obstructions, Fort McHenry, supporting batteries, stores, and communications. Labor came from across the city, including free and enslaved Black workers. The defense was not a spontaneous burst of patriotic feeling. It was a constructed system.</p><p>On September 12, John Stricker's militia fought a delaying action at North Point. British commander Robert Ross was mortally wounded. Stricker withdrew in order to the city's main defenses. The British held the battlefield but faced a much stronger line at Hampstead Hill. At the harbor, bomb vessels and a rocket ship shelled Fort McHenry and supporting works through rain and darkness. A nighttime boat movement failed. Unable to force the harbor or justify an assault on the earthworks, the expedition withdrew.</p><p>Francis Scott Key saw the flag in the morning and wrote the verses that became “The Star-Spangled Banner.” The immense flag had been produced in Mary Pickersgill's household, where Grace Wisher, a young African American indentured servant, also worked. The object belongs to her history too.</p></section>
        <section><span className="big-number">08</span><h2>Peace, then New Orleans</h2><p>At Ghent, Britain initially pressed demands that included an Indigenous buffer state in the Old Northwest. The United States rejected it, and Britain abandoned it as battlefield leverage weakened and other priorities returned. The treaty signed December 24 restored conquered territory. It did not settle impressment or neutral maritime rights. It required peace with Native nations and nominal restoration of their 1811 possessions, without a mechanism capable of restraining American expansion.</p><p>News traveled by sail. British and American forces near New Orleans did not know peace had been signed. Jackson assembled an unusually diverse defense: regulars, Louisiana militia, free Black battalions, Creoles, Tennessee and Kentucky militia, Choctaw fighters, Baratarians, sailors, and others. The British force included imperial regulars, Royal Marines, sailors, and Black soldiers of the West India Regiments. On January 8, 1815, the main British assault failed with enormous casualties.</p><p>The victory did not cause the treaty. It mattered profoundly to the people present, to Jackson's political rise, and to American memory. Traditions also place Filipino or “Manilamen” participants among the defenders; early Filipino presence in Louisiana is real, while the number and organization of fighters at Chalmette remain unresolved in contemporary documentation.</p></section>
        <section><span className="big-number">09</span><h2>No single answer to “who won?”</h2><p>The United States won no territory and no treaty language on impressment. It emerged with heightened nationalism and a powerful story of survival. Britain preserved British North America and ended a secondary war without sacrificing its central interests. Later Canadians remembered successful resistance, though modern Canada did not yet exist as a sovereign state.</p><p>For many Indigenous nations, the outcome was catastrophic. Britain abandoned the buffer-state proposal, Native leverage collapsed, and American land-taking accelerated. Thousands of Black refugees escaped American slavery through British lines; some resettled in Nova Scotia, while former Colonial Marines and families formed communities in Trinidad. Black Americans who served the United States returned to continuing slavery and racial exclusion.</p><p>The treaty restored a map between governments. It did not restore the balance of power among everyone who had fought. That is why the whole war cannot be reduced to one winner, one anthem, one border, or one national memory.</p>
          <div className="continue-box"><p>You have the shape. Now follow the sequence.</p><Link className="primary-action" href="/story/world-already-at-war">Read the whole story →</Link></div>
        </section>
      </article>
      <SourceList ids={["loc-guide","nara-war","cwm","lac","nps-indigenous","nhhc","nps-freedom-1","loc-ghent","nps-legacies"]} heading="Sources for the overview" />
    </main>
  );
}
