export type BaltimoreYear = "1812" | "1814";
export type BaltimoreMoment = { time: string; title: string; copy: string; source: string };
export type BaltimoreSite = { id: string; year: BaltimoreYear | "both"; name: string; kicker: string; copy: string; x: number; y: number; precision: "documented site" | "approximate corridor" | "regional position"; href?: string };

export const baltimoreMoments: Record<BaltimoreYear, BaltimoreMoment[]> = {
  "1812": [
    { time: "18 June", title: "War is declared", copy: "Madison signs the declaration after divided congressional votes. In heavily Republican Baltimore, opposition is quickly described as disloyalty rather than ordinary dissent.", source: "house-declaration" },
    { time: "22 June", title: "The first press is destroyed", copy: "A crowd converges on the Federal Republican office on Gay Street, tears down the building, and destroys its printing equipment. City authorities do not prevent the attack.", source: "nps-riots" },
    { time: "Late June–July", title: "Hanson refuses silence", copy: "Alexander Contee Hanson arranges to print outside Baltimore and prepares to resume circulation. Federalist supporters decide that the press must be defended physically if municipal government will not protect it.", source: "msa-hanson" },
    { time: "27 July · evening", title: "The Charles Street house is besieged", copy: "A crowd surrounds the brick house at 45 South Charles Street. Hanson, James M. Lingan, Henry Lee, and other armed defenders remain inside. Stones, gunfire, injuries, and deaths turn confrontation into siege.", source: "riot-narrative" },
    { time: "28 July · dawn", title: "Officials negotiate a surrender", copy: "Mayor Edward Johnson and militia officers persuade the defenders to leave under an assurance of protection. They are marched roughly a mile through hostile streets to the city jail.", source: "riot-narrative" },
    { time: "28 July · night", title: "The jail becomes the killing ground", copy: "A mob enters the jail and attacks prisoners placed there for safety. Lingan is murdered. Lee, Hanson, and others are tortured and gravely injured. The failure is institutional as well as personal.", source: "nps-riots" },
    { time: "Afterward", title: "Condemnation without civic reckoning", copy: "Maryland legislators condemn the negligence of local officials. Partisans continue to justify or minimize the violence. The murdered general never becomes central to Baltimore’s public identity.", source: "nps-riots" },
  ],
  "1814": [
    { time: "1813–1814", title: "A city prepares over time", copy: "Blockade, raids, privateering, shipbuilding, powder production, earthwork construction, and early-warning systems turn the Baltimore region into an organized defensive landscape.", source: "nps-baltimore-north-point" },
    { time: "11 September", title: "The warning reaches the city", copy: "Shore stations report British movement. Signals and mounted couriers carry the warning toward Federal Hill; alarm guns call troops to muster and residents to prepare.", source: "nps-baltimore-north-point" },
    { time: "12 September", title: "North Point buys time", copy: "About 3,200 Americans under John Stricker meet roughly 4,500 British troops. Robert Ross is mortally wounded. Stricker withdraws in order toward Baltimore’s main defenses.", source: "nps-baltimore-north-point" },
    { time: "13 September · land", title: "Brooke sees the earthworks", copy: "The British advance encounters the entrenched line centered on Hampstead Hill. Thousands of defenders, extensive works, and massed artillery make a direct assault extraordinarily costly.", source: "nps-baltimore-north-point" },
    { time: "13 September · water", title: "Bomb vessels attack the harbor", copy: "British bombs and rockets fall around Fort McHenry and the harbor defenses from beyond the effective range of most American guns. Rain, smoke, and darkness limit what witnesses can know.", source: "nps-bombardment" },
    { time: "14 September · night", title: "The flanking attempt fails", copy: "British boats move toward Ferry Branch. Fire from Fort Covington, Fort Babcock, and nearby batteries helps prevent a rear approach to Fort McHenry and the city.", source: "nps-baltimore-north-point" },
    { time: "14 September · morning", title: "The expedition withdraws", copy: "The water approach has failed and the land defenses remain intact. The flag tells observers that Fort McHenry has not surrendered; the British army returns to its transports.", source: "nps-baltimore" },
  ],
};

export const baltimoreSites: BaltimoreSite[] = [
  { id: "gay-street", year: "1812", name: "Federal Republican office", kicker: "Gay Street · June 1812", copy: "The newspaper’s first Baltimore office was destroyed. The marker is an approximate street corridor because the source establishes Gay Street, not a safely mappable surviving address.", x: 46, y: 37, precision: "approximate corridor" },
  { id: "charles-street", year: "1812", name: "Charles Street house", kicker: "45 South Charles Street · July 1812", copy: "Hanson and his supporters defended a rented brick house here before accepting an official escort to jail. The historic street address is documented; the building does not survive.", x: 38, y: 46, precision: "documented site" },
  { id: "city-jail", year: "1812", name: "Baltimore city jail", kicker: "Jones Falls jail complex · July 1812", copy: "The defenders were placed in official custody here and attacked by a mob. Later jail construction transformed the complex; this point marks the documented institutional site, not a surviving 1812 structure.", x: 56, y: 24, precision: "documented site" },
  { id: "fells-point", year: "1814", name: "Fell’s Point", kicker: "Privateering and shipbuilding", copy: "The waterfront helped make Baltimore a British target. The National Park Service records 122 federal letters of marque issued to Baltimore privateers during the war; claims about prizes require a separate count and should not be attributed to that page.", x: 67, y: 51, precision: "regional position" },
  { id: "hampstead-hill", year: "1814", name: "Hampstead Hill", kicker: "The main land defenses", copy: "A mile-long system of earthworks centered on today’s Patterson Park confronted the British advance. Black and white, enslaved and free laborers helped construct it.", x: 72, y: 27, precision: "documented site", href: "/story/baltimore-holds" },
  { id: "fort-mchenry", year: "1814", name: "Fort McHenry", kicker: "Harbor defense", copy: "The fort guarded the water approach as one part of a larger network that included batteries, obstructions, sailors, militia, and supporting works.", x: 50, y: 79, precision: "documented site", href: "/places/fort-mchenry" },
  { id: "ferry-branch", year: "1814", name: "Ferry Branch batteries", kicker: "Forts Covington and Babcock", copy: "These works helped defeat the nighttime boat movement that threatened Fort McHenry’s rear and Baltimore’s western defenses.", x: 31, y: 72, precision: "regional position" },
  { id: "battle-monument", year: "both", name: "Battle Monument", kicker: "What the city chose to remember", copy: "Begun in 1815, the monument names Baltimore’s military dead and became the city seal’s central image. No comparable civic landmark organizes memory of Lingan’s murder.", x: 44, y: 32, precision: "documented site" },
];
