import { humanIndexRecords, resolvePersonSlug } from "@/lib/human-record";

export type CatalogKind = "people" | "places" | "ships" | "documents" | "objects";

export type CatalogRecord = {
  slug: string;
  name: string;
  kind: CatalogKind;
  eyebrow: string;
  dates?: string;
  role: string;
  summary: string;
  significance: string;
  chapter?: string;
  sourceRefs: string[];
  aliases?: string[];
  recordDepth?: "dossier" | "index";
  facts?: { label: string; value: string }[];
  evidence?: "Documented" | "Strongly supported" | "Plausible / inferential" | "Oral tradition / community memory" | "Disputed" | "Unresolved";
};

export const curatedPeople: CatalogRecord[] = [
  { slug:"alexander-contee-hanson", name:"Alexander Contee Hanson", kind:"people", eyebrow:"Editor · Federalist politician", dates:"1786–1819", role:"Publisher of the Federal Republican and target of the Baltimore mobs", summary:"Hanson opposed the declaration of war in uncompromising language. After a crowd destroyed his Gay Street office, he resumed publication and joined armed supporters in defending a Charles Street house on July 27, 1812.", significance:"His beating, imprisonment, later congressional service, and early death make press freedom inseparable from the physical danger of wartime dissent.", chapter:"baltimore-at-war-with-itself", sourceRefs:["nps-riots","msa-hanson","riot-narrative"] },
  { slug:"james-madison", name:"James Madison", kind:"people", eyebrow:"President · United States", dates:"1751–1836", role:"President and wartime commander in chief", summary:"Madison asked Congress for war in June 1812 and led a government whose constitutional theory, finances, military administration, and political coalition were all tested by it.", significance:"His war message assembled maritime, commercial, territorial, and security grievances without reducing the case to one cause. The war nearly broke his government, yet its conclusion strengthened the party system he led.", chapter:"why-war", sourceRefs:["house-declaration","loc-guide"] },
  { slug:"james-m-lingan", name:"James M. Lingan", kind:"people", eyebrow:"Revolutionary veteran · Federalist", dates:"1751–1812", role:"Defender of the Federal Republican", summary:"A Revolutionary War officer and former prisoner on the British prison ship Jersey, Lingan joined the armed defense of Alexander Contee Hanson’s antiwar newspaper in Baltimore.", significance:"A mob murdered him in the city jail on July 28, 1812. Naming him prevents the Baltimore riots from dissolving into euphemism: Americans killed a Revolutionary general over the new war.", chapter:"baltimore-at-war-with-itself", sourceRefs:["nps-riots","bca"] },
  { slug:"henry-lee", name:"Henry “Light-Horse Harry” Lee", aliases:["Henry Lee", "Light-Horse Harry Lee"], kind:"people", eyebrow:"Revolutionary general · Federalist", dates:"1756–1818", role:"Defender of the Federal Republican", summary:"The celebrated Revolutionary cavalry commander joined Hanson and other Federalists in Baltimore, was taken to jail under official protection, and was savagely beaten when the mob entered.", significance:"Lee survived but never fully recovered. His suffering connects Revolutionary memory, violent party conflict, and the family history later overshadowed by his son Robert E. Lee.", chapter:"baltimore-at-war-with-itself", sourceRefs:["nps-riots"] },
  { slug:"tecumseh", name:"Tecumseh", kind:"people", eyebrow:"Shawnee leader · Indigenous coalition", dates:"c. 1768–1813", role:"Diplomat, strategist, and coalition builder", summary:"Tecumseh worked across Native nations and communities to resist piecemeal land cessions and build a political and military coalition capable of checking American expansion.", significance:"His alliance with Britain was strategic, not subordinate. His death at the Thames weakened the coalition and helped make Indigenous diplomatic exclusion at Ghent catastrophic.", chapter:"war-for-the-interior", sourceRefs:["nps-indigenous","lac"] },
  { slug:"tenskwatawa", name:"Tenskwatawa", kind:"people", eyebrow:"Shawnee religious leader", dates:"1775–1836", role:"Religious and political leader at Prophetstown", summary:"Known as the Prophet, Tenskwatawa led a program of spiritual renewal and resistance to accommodation that helped make Prophetstown a center of intertribal organizing.", significance:"His presence keeps the coalition story from becoming a biography of Tecumseh alone and reveals that resistance drew on religious, social, and political transformation as well as battlefield strategy.", chapter:"world-already-at-war", sourceRefs:["nps-indigenous"] },
  { slug:"isaac-brock", name:"Isaac Brock", kind:"people", eyebrow:"British Army · Upper Canada", dates:"1769–1812", role:"Major general and civil administrator", summary:"Brock used speed, bluff, and alliance with Tecumseh to compel Hull’s surrender at Detroit, then died leading a counterattack at Queenston Heights.", significance:"He became central to later Canadian memory, but his strategic aims were British imperial aims distinct from both later Canadian nationalism and Tecumseh’s defense of Native autonomy.", chapter:"easy-conquest-that-wasnt", sourceRefs:["cwm","lac"] },
  { slug:"william-hull", name:"William Hull", kind:"people", eyebrow:"United States Army", dates:"1753–1825", role:"Brigadier general and governor of Michigan Territory", summary:"Hull led the first American invasion from Detroit, withdrew, and surrendered the fort and his army to a smaller British, Canadian, and Indigenous force.", significance:"His collapse exposes the gap between American assumptions of easy conquest and the realities of command, supply, morale, and Indigenous military power.", chapter:"easy-conquest-that-wasnt", sourceRefs:["cwm","lac"] },
  { slug:"oliver-hazard-perry", name:"Oliver Hazard Perry", kind:"people", eyebrow:"United States Navy", dates:"1785–1819", role:"Commander at Lake Erie", summary:"Perry supervised the creation of an inland squadron and won the Battle of Lake Erie on September 10, 1813.", significance:"The victory mattered not simply as a naval duel but because it forced the British evacuation of Detroit and made Harrison’s pursuit to the Thames possible.", chapter:"war-for-the-interior", sourceRefs:["nps-lake-erie","nhhc"] },
  { slug:"david-porter", name:"David Porter", kind:"people", eyebrow:"United States Navy · Pacific", dates:"1780–1843", role:"Captain of USS Essex", summary:"Porter carried the war around Cape Horn, disrupted British whaling, accumulated prizes, intervened at Nuku Hiva, and lost Essex off Valparaíso.", significance:"His cruise makes the war’s global geography impossible to ignore while raising questions about American power and Indigenous Polynesian agency.", chapter:"war-around-cape-horn", sourceRefs:["nhhc-pacific"] },
  { slug:"richard-pierpoint", name:"Richard Pierpoint", kind:"people", eyebrow:"Black Loyalist · Upper Canada", dates:"c. 1744–c. 1837", role:"Militia organizer and veteran", summary:"Born in West Africa, enslaved and taken to North America, Pierpoint gained freedom through Loyalist service and later helped organize Black militia service in Upper Canada.", significance:"His life joins the Revolution, Black Loyalist migration, settlement in Upper Canada, and the War of 1812, histories that are often divided into separate national boxes.", chapter:"easy-conquest-that-wasnt", sourceRefs:["parks-pierpoint","parks-black-militia"] },
  { slug:"joshua-barney", name:"Joshua Barney", kind:"people", eyebrow:"United States Navy · Chesapeake", dates:"1759–1818", role:"Commander of the Chesapeake Flotilla", summary:"A Revolutionary naval veteran and privateer, Barney created a small flotilla to resist British movements in the Chesapeake and later fought on land at Bladensburg.", significance:"His sailors and marines made one of the firmest stands in an otherwise broken defense, connecting naval operations, underwater archaeology, and the burning of Washington.", chapter:"washington-burns", sourceRefs:["nhhc-flotilla"] },
  { slug:"alexander-cochrane", name:"Alexander Cochrane", kind:"people", eyebrow:"Royal Navy", dates:"1758–1832", role:"Commander in chief on the North American station", summary:"Cochrane directed major British coastal operations and issued the April 1814 proclamation offering reception, service, or resettlement to people leaving the United States.", significance:"The proclamation was simultaneously British wartime strategy and a real opportunity seized by enslaved people pursuing freedom.", chapter:"washington-burns", sourceRefs:["nps-freedom-1","nps-colonial"] },
  { slug:"robert-ross", name:"Robert Ross", kind:"people", eyebrow:"British Army · Chesapeake", dates:"1766–1814", role:"Major general commanding the Chesapeake expedition", summary:"Ross led the force that defeated the Americans at Bladensburg and burned public buildings in Washington. He was mortally wounded during the advance from North Point.", significance:"His death altered British command just as the expedition encountered Baltimore’s prepared defenses.", chapter:"baltimore-holds", sourceRefs:["nps-north-point","nps-baltimore"] },
  { slug:"john-stricker", name:"John Stricker", kind:"people", eyebrow:"Maryland militia", dates:"1758–1825", role:"Brigadier general at North Point", summary:"Stricker deployed Baltimore militia across the North Point road, fought the British advance, and withdrew in order toward the city’s main defenses.", significance:"His action shows why a battlefield withdrawal can still accomplish a defensive purpose: time, casualties, preserved forces, and a stronger line waiting behind him.", chapter:"baltimore-holds", sourceRefs:["nps-north-point"] },
  { slug:"samuel-smith", name:"Samuel Smith", kind:"people", eyebrow:"Maryland militia · Baltimore", dates:"1752–1839", role:"Major general directing Baltimore’s defense", summary:"A merchant, politician, Revolutionary veteran, and militia officer, Smith coordinated Baltimore’s land defenses, troops, artillery, and civic mobilization.", significance:"The city held because defense was a system built over time, not because one fort or one flag performed a miracle.", chapter:"baltimore-holds", sourceRefs:["nps-baltimore","bca"] },
  { slug:"mary-pickersgill", name:"Mary Pickersgill", kind:"people", eyebrow:"Flag maker · Baltimore", dates:"1776–1857", role:"Maker of Fort McHenry’s large flags", summary:"Pickersgill’s household produced the storm flag and enormous garrison flag ordered for Fort McHenry in 1813.", significance:"The flag was an object of skilled commercial labor before it became a national relic. Its production draws women’s work and household labor into military history.", chapter:"baltimore-holds", sourceRefs:["smithsonian-flag","nps-grace"] },
  { slug:"grace-wisher", name:"Grace Wisher", kind:"people", eyebrow:"Indentured girl · Baltimore", dates:"life dates unknown", role:"Worker in Mary Pickersgill’s household", summary:"Grace Wisher was a young African American indentured servant in the Pickersgill household when the Fort McHenry flags were made.", significance:"Her documented presence changes the object’s story. The Star-Spangled Banner was produced within Baltimore’s racial, legal, household, and labor systems, not by a solitary patriotic heroine.", chapter:"baltimore-holds", sourceRefs:["nps-grace","smithsonian-flag"] },
  { slug:"francis-scott-key", name:"Francis Scott Key", kind:"people", eyebrow:"Lawyer and poet", dates:"1779–1843", role:"Witness to the bombardment and author of the lyric", summary:"Key observed the attack while detained aboard an American truce vessel after helping secure William Beanes’s release. The morning flag inspired his poem.", significance:"Separating what Key could observe from what later imagery added makes the anthem’s origin more historically powerful, not less.", chapter:"baltimore-holds", sourceRefs:["nps-bombardment","smithsonian-flag"] },
  { slug:"thomas-macdonough", name:"Thomas Macdonough", kind:"people", eyebrow:"United States Navy · Lake Champlain", dates:"1783–1825", role:"Commander at Plattsburgh", summary:"Macdonough anchored his squadron in Plattsburgh Bay and prepared it to rotate damaged ships, allowing fresh broadsides to decide the battle.", significance:"His victory made a major British land invasion logistically untenable and changed expectations at Ghent.", chapter:"plattsburgh", sourceRefs:["nps-plattsburgh"] },
  { slug:"andrew-jackson", name:"Andrew Jackson", kind:"people", eyebrow:"United States Army · Gulf", dates:"1767–1845", role:"Major general in the southern campaigns", summary:"Jackson defeated Red Stick resistance, imposed the Treaty of Fort Jackson, seized Pensacola, organized New Orleans’s defense, and became the war’s most politically consequential hero.", significance:"Treating New Orleans without Horseshoe Bend and the coerced land cession turns regional conquest into a clean patriotic finale.", chapter:"new-orleans", sourceRefs:["nps-creek","nps-new-orleans-black"] },
  { slug:"menawa", name:"Menawa", kind:"people", eyebrow:"Red Stick Muscogee leader", dates:"c. 1765–c. 1836", role:"Leader at Horseshoe Bend", summary:"Menawa helped organize the fortified Red Stick position at Tohopeka and survived severe wounds after the American assault.", significance:"His story keeps Horseshoe Bend centered on Muscogee political struggle rather than using it merely as Andrew Jackson’s opening act.", chapter:"southern-borderlands", sourceRefs:["nps-creek"] },
  { slug:"prince-witten", name:"Prince Witten", kind:"people", eyebrow:"Black Spanish militiaman · Florida", dates:"active early 1800s", role:"Militia leader and defender of Spanish authority", summary:"Witten’s career belonged to the multiracial military and political world of Spanish Florida during American-backed incursions.", significance:"He reveals that Florida could function as sanctuary, imperial borderland, and a target of American expansion all at once.", chapter:"southern-borderlands", sourceRefs:["nps-prince-witten"] },
  { slug:"jordan-noble", name:"Jordan Noble", kind:"people", eyebrow:"Free Black musician · Louisiana", dates:"c. 1800–1890", role:"Drummer associated with the New Orleans campaign", summary:"Noble was a young free Black drummer whose long life later connected the Battle of New Orleans to public commemoration.", significance:"He offers a named life within the city’s much larger free Black military participation, while later recollection must be separated from contemporary documentation.", chapter:"new-orleans", sourceRefs:["nps-new-orleans-black"] },
];

const corePersonSlugs = new Set(curatedPeople.map((record) => record.slug));
const seenHumanSlugs = new Set<string>();
export const people: CatalogRecord[] = [
  ...curatedPeople.map((record) => ({ ...record, recordDepth:"dossier" as const })),
  ...humanIndexRecords.filter((record) => {
    if (corePersonSlugs.has(record.slug) || seenHumanSlugs.has(record.slug)) return false;
    seenHumanSlugs.add(record.slug);
    return true;
  }).map((record) => ({
    slug:record.slug,
    name:record.name,
    kind:"people" as const,
    eyebrow:record.group,
    role:record.role,
    summary:`${record.name} is preserved as a research lead in the ${record.group.toLowerCase()} index. This entry does not yet contain an individualized biography.`,
    significance:record.scopeNote,
    sourceRefs:record.sourceRefs,
    aliases:record.aliases,
    recordDepth:"index" as const,
    facts:[{label:"Record depth",value:"Research-index entry; person-specific reconciliation remains incomplete"}],
  })),
];

export const places: CatalogRecord[] = [
  { slug:"baltimore", name:"Baltimore", kind:"places", eyebrow:"Maryland · Chesapeake", role:"Political battleground, privateering port, and fortified city", summary:"Baltimore appears at both ends of the American wartime narrative: murderous partisan violence in 1812 and mass defensive mobilization in 1814.", significance:"The two episodes reveal that wartime unity was created, contingent, and layered over civic conflict.", chapter:"baltimore-at-war-with-itself", sourceRefs:["nps-riots","nps-baltimore","bca"] },
  { slug:"detroit", name:"Detroit", kind:"places", eyebrow:"Michigan Territory · Great Lakes", role:"Fort, settlement, and gateway to the interior", summary:"Hull surrendered Detroit in August 1812; American forces recovered it after Perry’s Lake Erie victory forced British withdrawal.", significance:"Detroit joins lake control, Indigenous alliance, supply, occupation, and the failure of the first invasion strategy.", chapter:"easy-conquest-that-wasnt", sourceRefs:["cwm","lac"] },
  { slug:"queenston-heights", name:"Queenston Heights", kind:"places", eyebrow:"Upper Canada · Niagara", role:"Escarpment battlefield above the Niagara River", summary:"American troops gained the heights in October 1812 but were isolated when reinforcements refused to cross. British, Canadian, and Indigenous forces retook the position.", significance:"The battle killed Brock and exposed the operational limits of American militia and cross-river invasion.", chapter:"easy-conquest-that-wasnt", sourceRefs:["cwm","lac"] },
  { slug:"sackets-harbor", name:"Sackets Harbor", kind:"places", eyebrow:"New York · Lake Ontario", role:"Principal American inland naval base", summary:"Sackets Harbor became a shipbuilding, supply, and command center for the Lake Ontario contest.", significance:"Its yards demonstrate that the lake war was an industrial and logistical arms race before it was a series of battles.", chapter:"continental-naval-arms-race", sourceRefs:["lac","nhhc"] },
  { slug:"kingston", name:"Kingston", kind:"places", eyebrow:"Upper Canada · Lake Ontario", role:"British naval and logistical base", summary:"Kingston anchored British power on Lake Ontario, supporting ships, troops, and the communications route to the upper province.", significance:"Its survival constrained American strategy and helps explain why neither fleet risked decisive destruction lightly.", chapter:"continental-naval-arms-race", sourceRefs:["lac"] },
  { slug:"nuku-hiva", name:"Nuku Hiva", kind:"places", eyebrow:"Marquesas Islands · Pacific", role:"Polynesian island and Essex refitting base", summary:"Porter refitted his squadron, intervened in local conflicts, and announced an American claim without durable effect.", significance:"The site forces the Pacific campaign to be told through Polynesian agency rather than as empty geography in an American naval adventure.", chapter:"war-around-cape-horn", sourceRefs:["nhhc-pacific"] },
  { slug:"york", name:"York", kind:"places", eyebrow:"Upper Canada · Lake Ontario", role:"Colonial capital attacked in 1813", summary:"American forces captured York; looting and burning became part of a widening cycle of destruction and later retaliation claims.", significance:"York makes civilian property, military discipline, occupation, and memory part of campaign history.", chapter:"war-reaches-homes", sourceRefs:["cwm","lac"] },
  { slug:"havre-de-grace", name:"Havre de Grace", kind:"places", eyebrow:"Maryland · Chesapeake", role:"Upper-bay town raided in 1813", summary:"British forces burned and plundered much of Havre de Grace during their expanding Chesapeake operations.", significance:"The raid marks the point where blockade and naval presence became direct war against local homes and property.", chapter:"war-reaches-homes", sourceRefs:["nps-living"] },
  { slug:"horseshoe-bend", name:"Horseshoe Bend", kind:"places", eyebrow:"Muscogee homelands · Tallapoosa River", role:"Fortified Red Stick position at Tohopeka", summary:"Jackson’s American, Cherokee, and allied Muscogee army broke Red Stick resistance here in March 1814.", significance:"The battlefield belongs within Muscogee civil conflict, American expansion, and the land cession that followed, rather than merely within Jackson’s biography.", chapter:"southern-borderlands", sourceRefs:["nps-creek"] },
  { slug:"pensacola", name:"Pensacola", kind:"places", eyebrow:"Spanish West Florida · Gulf", role:"Spanish port contested by British and American power", summary:"British forces used Spanish Pensacola; Jackson captured the town in November 1814 before moving toward New Orleans.", significance:"Pensacola shows how formally Spanish territory became part of Anglo-American war and U.S. expansion.", chapter:"southern-borderlands", sourceRefs:["nps-prince-witten"] },
  { slug:"plattsburgh", name:"Plattsburgh", kind:"places", eyebrow:"New York · Lake Champlain", role:"Land-and-water defensive position", summary:"Macomb’s defenders and Macdonough’s squadron checked a major British invasion in September 1814.", significance:"The place makes the relationship between fleet, supply, land invasion, and diplomacy unusually visible.", chapter:"plattsburgh", sourceRefs:["nps-plattsburgh"] },
  { slug:"bladensburg", name:"Bladensburg", kind:"places", eyebrow:"Maryland · Washington approaches", role:"Battlefield opening the road to the capital", summary:"Poorly coordinated American lines collapsed here on August 24, 1814, though Barney’s sailors and marines resisted fiercely.", significance:"Bladensburg was not simply national farce; it was a command failure with direct consequences for a city and its people.", chapter:"washington-burns", sourceRefs:["nhhc-flotilla"] },
  { slug:"north-point", name:"North Point", kind:"places", eyebrow:"Maryland · Patapsco Neck", role:"Approach battlefield outside Baltimore", summary:"Stricker’s militia delayed the British advance on September 12, 1814; Ross was mortally wounded nearby.", significance:"Its value lay in time and preservation of the defense, showing why tactical possession of ground is not the only measure of outcome.", chapter:"baltimore-holds", sourceRefs:["nps-north-point"] },
  { slug:"fort-mchenry", name:"Fort McHenry", kind:"places", eyebrow:"Baltimore Harbor · Maryland", role:"Harbor fort and national memory site", summary:"Fort McHenry and supporting batteries denied the British water approach during the September 1814 attack.", significance:"The fort mattered as one element of a layered defense; its later symbolic prominence should not erase the earthworks, harbor batteries, and labor behind it.", chapter:"baltimore-holds", sourceRefs:["nps-bombardment","smithsonian-flag"] },
  { slug:"ghent", name:"Ghent", kind:"places", eyebrow:"United Kingdom of the Netherlands", role:"Site of the peace negotiations", summary:"American and British commissioners negotiated here through changing military news and shifting demands in 1814.", significance:"Ghent turns diplomacy into part of the war’s action: armies and fleets changed what negotiators believed could be demanded.", chapter:"peace-at-ghent", sourceRefs:["loc-ghent"] },
  { slug:"chalmette", name:"Chalmette", kind:"places", eyebrow:"Louisiana · Lower Mississippi", role:"Defensive line below New Orleans", summary:"Jackson’s coalition defended the Rodriguez Canal line against the main British assault on January 8, 1815.", significance:"The landscape helps explain the battle’s asymmetrical losses while the participants reveal the city’s multiracial and imperial world.", chapter:"new-orleans", sourceRefs:["nps-new-orleans-black","nps-choctaw"] },
];

export const ships: CatalogRecord[] = [
  { slug:"uss-constitution", name:"USS Constitution", kind:"ships", eyebrow:"United States Navy · Heavy frigate", role:"44-gun frigate", summary:"Constitution defeated Guerriere and Java in 1812 and Cyane and Levant in 1815, becoming the war’s most durable American naval icon.", significance:"Its victories mattered psychologically and tactically without overturning British command of the Atlantic.", chapter:"old-ironsides", sourceRefs:["nhhc"], facts:[{label:"Launched",value:"1797"},{label:"Relevant commander",value:"Isaac Hull / William Bainbridge"},{label:"Famous name",value:"“Old Ironsides”"}] },
  { slug:"hms-guerriere", name:"HMS Guerriere", kind:"ships", eyebrow:"Royal Navy · Frigate", role:"38-gun frigate", summary:"Guerriere fought Constitution on August 19, 1812, and was so badly damaged that the Americans burned the captured hull.", significance:"The defeat supplied the United States with its first great naval symbol while prompting Britain to treat the heavy American frigates more cautiously.", chapter:"old-ironsides", sourceRefs:["nhhc"] },
  { slug:"uss-united-states", name:"USS United States", kind:"ships", eyebrow:"United States Navy · Heavy frigate", role:"44-gun frigate", summary:"Under Stephen Decatur, United States captured HMS Macedonian in October 1812 and brought the prize into an American port.", significance:"A captured enemy frigate was evidence the public could see, inspect, celebrate, and turn into political meaning.", chapter:"old-ironsides", sourceRefs:["nhhc"] },
  { slug:"uss-chesapeake", name:"USS Chesapeake", kind:"ships", eyebrow:"United States Navy · Frigate", role:"Frigate tied to two maritime crises", summary:"Chesapeake was fired upon by Leopard in 1807 and captured by Shannon in 1813 after a short, bloody action.", significance:"One hull connects the prewar sovereignty crisis to the war’s reversal of early American frigate triumphs.", chapter:"old-ironsides", sourceRefs:["nara-impressment","nhhc"] },
  { slug:"uss-lawrence", name:"USS Lawrence", kind:"ships", eyebrow:"United States Navy · Lake Erie", role:"Brig and Perry’s initial flagship", summary:"Lawrence absorbed devastating fire at Lake Erie before Perry transferred his flag and continued the battle from Niagara.", significance:"Its damage and Perry’s transfer show victory as endurance, fleet design, and squadron action, not a single invulnerable ship.", chapter:"war-for-the-interior", sourceRefs:["nps-lake-erie"] },
  { slug:"uss-niagara", name:"USS Niagara", kind:"ships", eyebrow:"United States Navy · Lake Erie", role:"Brig and Perry’s second flagship", summary:"Perry transferred to Niagara during the Battle of Lake Erie and used it in the final attack that broke the British line.", significance:"The paired histories of Lawrence and Niagara complicate iconography that centers only the famous flag and dispatch.", chapter:"war-for-the-interior", sourceRefs:["nps-lake-erie"] },
  { slug:"uss-essex", name:"USS Essex", kind:"ships", eyebrow:"United States Navy · Pacific", role:"Frigate and commerce raider", summary:"Essex rounded Cape Horn, attacked British whaling, operated from the Marquesas, and was captured near Valparaíso in March 1814.", significance:"No other American warship makes the conflict’s Pacific geography so vivid.", chapter:"war-around-cape-horn", sourceRefs:["nhhc-pacific"] },
  { slug:"uss-saratoga", name:"USS Saratoga", kind:"ships", eyebrow:"United States Navy · Lake Champlain", role:"Macdonough’s flagship", summary:"Anchored in Plattsburgh Bay, Saratoga used springs and kedges to rotate and bring a fresh broadside into the fight.", significance:"The ship’s handling illustrates why preparation and position could decide the fate of a land invasion.", chapter:"plattsburgh", sourceRefs:["nps-plattsburgh"] },
  { slug:"hms-confiance", name:"HMS Confiance", kind:"ships", eyebrow:"Royal Navy · Lake Champlain", role:"British flagship", summary:"Newly completed and carrying heavy guns, Confiance attacked Macdonough’s anchored line and was forced to surrender after a brutal exchange.", significance:"Its defeat left Prévost’s large army without secure control of the water route sustaining it.", chapter:"plattsburgh", sourceRefs:["nps-plattsburgh"] },
];

export const documents: CatalogRecord[] = [
  { slug:"madison-war-message", name:"Madison’s War Message", kind:"documents", eyebrow:"1 June 1812 · Presidential message", role:"Formal statement of grievances to Congress", summary:"Madison presented impressment, interference with commerce, violations of American waters, and British connections to frontier violence as evidence of a state of war.", significance:"Reading the message prevents later single-cause explanations from replacing the administration’s actual public case.", chapter:"why-war", sourceRefs:["loc-guide","house-declaration"] },
  { slug:"declaration-of-war", name:"Declaration of War", kind:"documents", eyebrow:"18 June 1812 · Federal statute", role:"Legal beginning of war between the United States and Britain", summary:"Congress authorized war after votes of 79–49 in the House and 19–13 in the Senate; Madison signed the measure on June 18.", significance:"The divided roll calls make domestic opposition visible at the moment of national action.", chapter:"why-war", sourceRefs:["house-declaration"] },
  { slug:"hanson-federal-republican", name:"The Federal Republican", kind:"documents", eyebrow:"Baltimore · Newspaper", role:"Federalist antiwar press", summary:"Alexander Contee Hanson’s newspaper attacked the war and Democratic-Republican leadership, provoking the destruction of its press and later armed confrontation.", significance:"The paper makes freedom of the press, partisan rhetoric, and municipal failure part of the war’s opening story.", chapter:"baltimore-at-war-with-itself", sourceRefs:["nps-riots","bca"] },
  { slug:"perry-dispatch", name:"Perry’s Lake Erie Dispatch", kind:"documents", eyebrow:"10 September 1813 · Naval dispatch", role:"Report of victory to William Henry Harrison", summary:"Perry’s famously concise report announced that the enemy squadron had become American property.", significance:"The exact wording matters because a dispatch became a motto, and a fleet victory became national shorthand detached from its logistical context.", chapter:"war-for-the-interior", sourceRefs:["nps-lake-erie"] },
  { slug:"cochrane-proclamation", name:"Cochrane’s Proclamation", kind:"documents", eyebrow:"2 April 1814 · British proclamation", role:"Offer of reception to people leaving the United States", summary:"Cochrane announced that people willing to emigrate from the United States would be received, with choices of military service or resettlement in British possessions.", significance:"It was a weapon against American slavery and a real opening through which enslaved people pursued freedom.", chapter:"blockade", sourceRefs:["nps-freedom-1","nps-colonial"] },
  { slug:"treaty-fort-jackson", name:"Treaty of Fort Jackson", kind:"documents", eyebrow:"9 August 1814 · Imposed land cession", role:"Agreement ending the Creek War campaign", summary:"The treaty compelled the Muscogee Confederacy to cede roughly 23 million acres, including territory belonging to communities allied with the United States.", significance:"Its terms reveal how wartime alliance could end in coerced dispossession.", chapter:"southern-borderlands", sourceRefs:["nps-creek"] },
  { slug:"defence-fort-mhenry", name:"Defence of Fort M’Henry", kind:"documents", eyebrow:"September 1814 · Broadside and lyric", role:"Francis Scott Key’s poem", summary:"Key’s verses circulated as a broadside and song before their first stanza became the United States national anthem more than a century later.", significance:"The document permits the immediate event, nineteenth-century circulation, and later national canonization to be kept distinct.", chapter:"baltimore-holds", sourceRefs:["nps-bombardment","smithsonian-flag"] },
  { slug:"treaty-of-ghent", name:"Treaty of Ghent", kind:"documents", eyebrow:"24 December 1814 · Peace treaty", role:"Agreement ending the Anglo-American war", summary:"The treaty restored conquered territory and established mechanisms for outstanding boundary questions while leaving maritime grievances largely unmentioned.", significance:"Its text distinguishes the peace governments actually made from the victories later national memories claimed.", chapter:"peace-at-ghent", sourceRefs:["loc-ghent"] },
];

export const objects: CatalogRecord[] = [
  { slug:"star-spangled-banner", name:"The Star-Spangled Banner", kind:"objects", eyebrow:"Flag · Smithsonian", role:"Fort McHenry’s great garrison flag", summary:"The enormous wool-and-cotton flag made in Mary Pickersgill’s household flew over Fort McHenry and later became a national relic.", significance:"Its material history includes Grace Wisher, skilled household labor, changing ownership, souvenir clipping, conservation, and the much later anthem.", chapter:"baltimore-holds", sourceRefs:["smithsonian-flag","nps-grace"], facts:[{label:"Maker",value:"Mary Pickersgill’s household"},{label:"Original size",value:"approximately 30 by 42 feet"},{label:"Repository",value:"Smithsonian NMAH"}] },
  { slug:"fort-mchenry-storm-flag", name:"Fort McHenry Storm Flag", kind:"objects", eyebrow:"Flag · 1813", role:"Smaller foul-weather flag", summary:"A smaller flag was ordered with the great garrison flag for use in bad weather at Fort McHenry.", significance:"Distinguishing the two flags prevents a familiar image from replacing the uncertain nighttime and morning chronology.", chapter:"baltimore-holds", sourceRefs:["nps-bombardment","smithsonian-flag"], evidence:"Strongly supported" },
  { slug:"congreve-rocket", name:"Congreve Rocket", kind:"objects", eyebrow:"Weapon · British artillery", role:"Rocket projectile and psychological weapon", summary:"British forces used Congreve rockets at Bladensburg and Baltimore, producing conspicuous trails, noise, and uncertain accuracy.", significance:"The object links technology, fear, battlefield myth, and the “rockets’ red glare” remembered through Key’s lyric.", chapter:"washington-burns", sourceRefs:["nps-bombardment"] },
  { slug:"protection-certificate", name:"Seaman’s Protection Certificate", kind:"objects", eyebrow:"Identity paper · Maritime labor", role:"Document carried to assert American citizenship", summary:"Protection certificates recorded personal characteristics intended to help American sailors resist impressment claims.", significance:"Their physical descriptions and frequent rejection expose how national identity at sea was documented, contested, and embodied.", chapter:"world-already-at-war", sourceRefs:["nara-impressment"] },
  { slug:"lake-erie-battle-flag", name:"“Don’t Give Up the Ship” Flag", kind:"objects", eyebrow:"Battle flag · Lake Erie", role:"Perry’s memorial signal", summary:"Perry used a blue flag bearing James Lawrence’s dying command during the Battle of Lake Erie.", significance:"It shows memory operating inside the war itself: a recent defeat converted into language for a later victory.", chapter:"war-for-the-interior", sourceRefs:["nps-lake-erie"] },
  { slug:"fort-mchenry-bombardment-print", name:"A View of the Bombardment of Fort McHenry", kind:"objects", eyebrow:"Print · c. 1819", role:"Early visual interpretation of the bombardment", summary:"John Bower’s hand-colored print presents bomb vessels, arcing shells, fortifications, and the harbor landscape several years after the event.", significance:"It is not an eyewitness photograph. Used critically, it shows how the bombardment was being visualized within the generation that experienced it.", chapter:"baltimore-holds", sourceRefs:["loc-fort-print"], facts:[{label:"Creator",value:"John Bower"},{label:"Date",value:"approximately 1819; later re-engraving"},{label:"Rights",value:"Library of Congress: no known restrictions"}] },
];

export const catalogByKind: Record<CatalogKind, CatalogRecord[]> = { people, places, ships, documents, objects };
export const allCatalogRecords = Object.values(catalogByKind).flat();
export const catalogRecord = (kind: string, slug: string) => {
  const resolvedSlug = kind === "people" ? resolvePersonSlug(slug) : slug;
  return (catalogByKind[kind as CatalogKind] || []).find((record) => record.slug === resolvedSlug);
};
