export type ChapterExpansion = { heading: string; paragraphs: string[]; voice: { label: string; excerpt: string; attribution: string; sourceRef: string } };

export const chapterExpansions: Record<string, ChapterExpansion> = {
  "world-already-at-war": { heading: "Pressure without peace", paragraphs: [
    "Neutral trade was never merely a contest among flags. American ships carried flour, tobacco, cotton, sugar, manufactured goods, migrants, and news through a world economy sustained by coercion. Sailors moved among ports and employers; citizenship papers attempted to make mobile lives legible to governments. When a boarding officer rejected a protection certificate, a diplomatic quarrel became confinement and forced labor. Merchants could insure cargo and petition officials, but an ordinary seaman had far fewer defenses against a warship that needed hands.",
    "The embargo exposed the limits of economic pressure. Closing American ports was meant to deny Britain and France the benefits of trade, yet enforcement fell most heavily on American merchants, workers, and coastal communities. Smuggling grew along the Canadian border. New England opposition sharpened. Congress replaced the embargo with narrower restrictions, but policy continued to chase events in Europe. Every adjustment produced winners, losses, and new arguments about how much hardship a republic could impose on its own citizens to avoid war.",
    "On the continent, Indigenous diplomacy connected villages, kinship networks, trade, and spiritual renewal across boundaries Americans treated as settled. Tecumseh's coalition was not a British invention. British supplies mattered, but the political project answered the repeated sale and survey of Native land. That distinction changes the cause of war: the western crisis was not simply foreign intrigue at the edge of the republic. It was a struggle over whether the United States could convert disputed treaties into farms, roads, forts, and jurisdiction."
  ], voice: { label: "A sailor's paper", excerpt: "Protection certificates recorded age, height, complexion, scars, and birthplace because a sailor might have to prove his national identity with his body.", attribution: "National Archives, impressed-seamen records", sourceRef: "nara-impressment" } },
  "why-war": { heading: "A decision made under uncertainty", paragraphs: [
    "Madison's list of injuries supplied a common vocabulary, not a common priority. Maritime communities could focus on seizures and impressment; western representatives could emphasize frontier violence and British support for Native resistance; party leaders could speak of national honor. Expansionists imagined different futures for Canada or Florida. These motives reinforced one another during debate even when they would not have produced the same peace terms. A responsible explanation therefore distinguishes the administration's declared case, congressional rhetoric, military planning, and the private ambitions of individual advocates.",
    "The vote also mapped political geography. Federalists warned that war would devastate commerce and strengthen executive power. Many Republicans believed that accepting repeated violations would reduce independence to a phrase. Neither camp possessed the future. War supporters underestimated the difficulty of invasion, finance, and mobilization; opponents sometimes underestimated the political cost of continued submission. Their disagreement belonged to a young constitutional system attempting its first declared war against a vastly more experienced empire.",
    "Timing added an enduring irony. Britain suspended the Orders in Council shortly before the American declaration, but Atlantic communication prevented the news from resolving the crisis in time. Impressment remained. Once fighting began, honor, casualties, territory, and alliance commitments created new obstacles to peace. The episode cautions against treating a policy change in London as a simple missed off-ramp: governments still had to learn of it, trust it, interpret it, and decide whether the remaining grievances justified retreat."
  ], voice: { label: "The war message", excerpt: "Madison asked Congress to consider whether British acts already amounted to a state of war against the United States.", attribution: "James Madison, message to Congress, 1 June 1812", sourceRef: "house-declaration" } },
  "baltimore-at-war-with-itself": { heading: "Violence before invasion", paragraphs: [
    "Baltimore's political economy made the city intensely pro-war but never unanimous. Its merchants and privateer investors saw opportunities in conflict; artisans and laborers joined public mobilization; Republican newspapers described Federalist resistance as disloyal. The Federal Republican answered with language that could be equally inflammatory. Printing was physical work conducted in visible offices, and destroying a press silenced both a political position and the livelihoods that carried it into public circulation.",
    "The July crisis was not a spontaneous instant. Hanson and his allies returned, armed themselves in a house, and exchanged gunfire with a crowd. Officials negotiated their removal to jail, supposedly for protection. The jail then failed as sanctuary. Naming that sequence matters because it distributes responsibility across attackers, armed defenders, magistrates, militia, and civic leaders without making the murder of prisoners inevitable or excusable. James Lingan's death and the torture of survivors became evidence for Federalists that Republican claims to liberty concealed organized coercion.",
    "Two years later the same city presented a different public face: trenches, militia units, supply work, and a shared determination to resist British attack. The contrast should remain visible. Defensive solidarity did not erase the victims of 1812, and the earlier riot does not make the later defense fraudulent. Together they show how civic unity is constructed, sometimes by cooperation, sometimes by forgetting, and sometimes by moving unacceptable conflict outside the commemorative frame."
  ], voice: { label: "The contested press", excerpt: "The surviving newspaper record preserves arguments against the war that Baltimore crowds attempted to suppress by destroying the means of publication.", attribution: "Federal Republican and Baltimore archival records", sourceRef: "bca" } },
  "easy-conquest-that-wasnt": { heading: "Invasion meets geography", paragraphs: [
    "The map made Canada look close; it did not make conquest easy. Roads were poor, waterways governed movement, supplies arrived slowly, and commanders answered to overlapping civil and military authorities. American forces attacked at Detroit, Niagara, and the St. Lawrence rather than through one coordinated system. A numerical advantage on paper could dissolve when militia terms expired, wagons failed, officers quarreled, or soldiers refused to cross an international boundary they believed their legal obligation did not cover.",
    "Brock and Tecumseh exploited uncertainty at Detroit. British regulars, Canadian militia, and Indigenous warriors were not interchangeable, but their combined presence allowed deception to magnify Hull's fears. The threat to civilians inside the fort and Hull's concern for scattered detachments influenced surrender. Calling the event cowardice may satisfy later memory; it explains less than age, command isolation, intelligence failures, and the real strategic power of an alliance Hull did not understand.",
    "Queenston Heights revealed another coalition. Haudenosaunee warriors fought on both sides of a border imposed through their homelands, while local militia and British regulars defended Upper Canada. Brock died leading a counterattack, creating a colonial hero. American troops gained the heights but became isolated. The prisoners and dead turned an assumed quick victory into proof that proximity was not control and that British North America contained active defenders with their own reasons to fight."
  ], voice: { label: "Hull's proclamation", excerpt: "The invasion began with assurances of protection and liberation; surrender followed before the summer was over.", attribution: "William Hull's 1812 proclamation and surrender record", sourceRef: "cwm" } },
  "old-ironsides": { heading: "Victory at the scale of a single deck", paragraphs: [
    "The heavy American frigates were unusually large, strongly built, and well armed for their nominal class. Their captains also benefited from trained crews and the ability to choose some engagements before the blockade tightened. Those advantages do not make the victories accidental, nor do they prove that American design alone defeated Britain at sea. Gunnery, damage control, weather, command judgment, and the condition of an opponent all shaped combats that unfolded at close range amid splinters, smoke, and casualties.",
    "News compressed that violence into names: Constitution and Guerriere, United States and Macedonian, Wasp and Frolic. Captured flags, public dinners, prints, and newspaper verse converted ship actions into national reassurance after disasters on land. Macedonian's arrival as a prize made victory material. Yet the Royal Navy could absorb individual losses and change its instructions. By 1813 its blockade restricted American warships and commerce with a force the United States could not match.",
    "The phrase ‘Old Ironsides’ belongs to this process of making memory. Constitution's oak sides did not literally become iron, and the famous nickname did not by itself explain the battle. It conveyed the astonishment of seeing enemy shot fail to end the ship's resistance. Holding tactical achievement beside strategic imbalance produces the fuller truth: American sailors earned striking victories, while Britain retained the capacity to contain most of the American coast."
  ], voice: { label: "A command becomes a motto", excerpt: "Don't give up the ship.", attribution: "Attributed to James Lawrence after the battle between Chesapeake and Shannon", sourceRef: "nhhc" } },
  "war-for-the-interior": { heading: "Waterways were the roads", paragraphs: [
    "Armies in the interior depended upon boats, lake fleets, portages, and fragile supply lines. Building a squadron required timber, iron, rope, canvas, guns, skilled shipwrights, and crews to reach remote yards. The vessels were military instruments and floating products of regional mobilization. Control of Lake Erie therefore meant more than winning a dramatic exchange of broadsides: it decided whether British forces at Detroit could be supplied and whether an American army could advance without exposing its rear.",
    "Perry's victory and Harrison's pursuit worked as a sequence. The damaged Lawrence, the transfer to Niagara, and the eventual capture of the British squadron became one of the war's most durable set pieces. The British then abandoned Detroit. At the Thames, their retreating line broke and Tecumseh was killed. American accounts often end there, with territorial recovery. For Native communities the death destroyed a leader and sharply reduced the coalition's ability to hold together across distance and different national interests.",
    "The famous dispatch, ‘We have met the enemy and they are ours,’ turned a complex squadron victory into a portable sentence. It named captured vessels but not the shipyard labor, Black sailors, ordinary seamen, or logistical network that made the encounter possible. The result remains decisive without becoming solitary. Lake control, land pursuit, alliance, and supply converted one another into strategic effect."
  ], voice: { label: "Perry's dispatch", excerpt: "We have met the enemy and they are ours.", attribution: "Oliver Hazard Perry to William Henry Harrison, 10 September 1813", sourceRef: "nps-lake-erie" } },
  "continental-naval-arms-race": { heading: "Fleets built in forests", paragraphs: [
    "Lake Ontario's contest rarely supplied the decisive battle both governments desired. Instead, shipbuilding itself became strategy. A new vessel could shift the balance and keep the opposing squadron in harbor; the answer was another larger ship, more guns, and additional labor. Sackets Harbor and Kingston functioned like industrial systems connected to distant foundries and supply routes. Master command of the lake remained elusive because neither side wished to risk its entire logistical advantage against a momentary favorable wind.",
    "The result was a war of feints, convoy protection, amphibious movement, and threat. Troops could be carried rapidly along the shore only when a fleet made the passage safe. Commanders judged naval and land operations together, sometimes badly. Raids might damage stores without destroying capacity; unfinished ships could shape choices before launching. The water linked settlements yet also separated forces whenever the opposing squadron appeared.",
    "This arms race complicates the language of naval glory. There was bravery, but also accounting: board feet, anchor weights, gun calibers, drafts, sickness, and desertion. Civilian craftspeople and coerced labor occupied the same strategic field as commodores. When peace arrived, incomplete ships and enlarged facilities recorded how close the inland war had come to producing fleets disproportionate to the communities supporting them."
  ], voice: { label: "The yard as evidence", excerpt: "Ship lists and construction records show strategy changing before vessels ever met in battle.", attribution: "Library and Archives Canada and naval records", sourceRef: "lac" } },
  "war-around-cape-horn": { heading: "An Atlantic war in the Pacific", paragraphs: [
    "Essex entered a Pacific already organized by Indigenous societies, Spanish American ports, British commerce, and global whaling. David Porter targeted a valuable British fleet whose oil connected distant hunting grounds to markets and industry. Captures gave him ships but also prisoners, maintenance problems, and crews of uncertain loyalty. Distance created opportunity because British protection was thin; it also made every replacement spar, neutral-port rule, and reliable report more consequential.",
    "At Nuku Hiva, American narratives long treated the island as a convenient base. That viewpoint turns inhabited land into scenery. Porter entered local conflicts, built a station, and proclaimed a claim the United States neither sustained nor effectively recognized. Nuku Hiva communities acted from their own rivalries and interests, not as supporting characters in a frigate captain's voyage. Violence there belongs to the history of the cruise as fully as captured whalers do.",
    "Near Valparaíso, damage, wind, and superior British force closed the campaign. Neutrality did not protect Essex once it left the harbor, and Phoebe and Cherub compelled surrender. Porter returned to celebrity, while the commercial damage he caused proved temporary. The voyage matters less as an alternative path to American command of the sea than as a demonstration that the war's networks reached around Cape Horn and into other peoples' worlds."
  ], voice: { label: "Porter's cruise", excerpt: "The captain's reports joined captured ships, distant islands, and a failed territorial claim into an American story of enterprise.", attribution: "U.S. naval records summarized by Naval History and Heritage Command", sourceRef: "nhhc-pacific" } },
  "war-reaches-homes": { heading: "Civilian property becomes strategy", paragraphs: [
    "York, Newark, the Niagara frontier, and Chesapeake towns experienced destruction in different circumstances. Some buildings were military targets; others were public property, shops, farms, or homes. Discipline weakened amid occupation and retreat. Commanders then placed each episode inside a moral ledger, presenting their own destruction as necessity and the enemy's as barbarity. The ledger traveled with armies and newspapers, making retaliation appear both emotional and administratively reasoned.",
    "For residents, the distinction between raid and campaign did not restore food, shelter, livestock, tools, or family papers. Flight itself had costs. Women, children, elderly people, free Black residents, enslaved laborers, and recent settlers encountered armed forces from unequal legal positions. Some bargained or concealed goods; some supplied troops; some escaped bondage; some were accused of disloyalty. Civilian experience was active but constrained, preserved unevenly because property claims and official correspondence survive more readily than fear.",
    "Havre de Grace demonstrates the intimate range of sea power. British boats could leave a squadron, enter rivers, land troops, and turn the upper bay into a threatened frontier. The raid was small beside continental battles but enormous to a household that lost its building or livelihood. Measuring war only by casualty tables would miss the way repeated alarms reorganized work, movement, and trust along an entire shoreline."
  ], voice: { label: "Claims after destruction", excerpt: "Petitions and damage accounts translate burned homes and lost goods into the formal language governments were prepared to record.", attribution: "Civilian conflict narratives and local records", sourceRef: "nps-living" } },
  blockade: { heading: "The coast under pressure", paragraphs: [
    "Britain tightened the blockade unevenly and then with growing reach. Major warships watched ports, cruisers intercepted commerce, and smaller vessels entered bays and rivers. Insurance rose, customs revenue fell, imported goods became scarce, and export crops accumulated. A policy applied from offshore therefore reached warehouses, shipyards, farms, and federal finance. Privateers could still escape and inflict losses, but their successes did not reopen trade on the scale the national economy required.",
    "The Chesapeake campaign joined blockade to intelligence. Watermen, pilots, refugees, prisoners, loyalists, and local residents carried knowledge through a landscape of creeks and plantations. British officers gathered supplies by purchase, seizure, or destruction. American militia tried to predict landings across too much shoreline. The result was not constant occupation but recurring vulnerability: households could not know whether sails on the horizon meant reconnaissance, trade interruption, liberation, or attack.",
    "For enslaved people, British presence could create a dangerous route toward freedom. Cochrane's proclamation formalized an offer, but people had already been testing the possibility of escape. Families weighed separation, retaliation, and an uncertain British future against bondage in the United States. Those who reached British lines became guides, sailors, laborers, soldiers, and refugees. Their decisions transformed the campaign and reveal why calling the proclamation merely propaganda is insufficient."
  ], voice: { label: "Cochrane's proclamation", excerpt: "People leaving the United States were offered reception, military service, or resettlement in British possessions.", attribution: "Admiral Alexander Cochrane, proclamation of 2 April 1814", sourceRef: "nps-freedom-1" } },
  "southern-borderlands": { heading: "Several wars occupy the same ground", paragraphs: [
    "The Creek War emerged from Muscogee political and religious conflict, pressure from American settlement, and a wider struggle over authority. ‘Red Stick’ and ‘friendly Creek’ were wartime categories that can hide town affiliations and changing choices. Cherokee and Lower Creek warriors joined Jackson for reasons of their own. Treating the campaign as a simple United States victory over a single enemy erases Native allies and turns a civil conflict into a preface to American expansion.",
    "Fort Mims brought terror and mobilization. Reports emphasized the deaths of settlers and defenders, while the mixed Muscogee world inside the stockade complicated later racial and national labels. American armies converged, often short of food and bound by militia service terms. At Horseshoe Bend the Red Stick position became a killing ground after allied Cherokee forces crossed the river and American artillery and infantry closed in.",
    "The Treaty of Fort Jackson exposed the destination of victory. Jackson demanded land not only from defeated Red Sticks but from Muscogee communities that had fought beside the United States. The cession opened millions of acres to American control. Pensacola and Spanish Florida added another imperial border where British agents, Spanish officials, Creek refugees, free and enslaved Black people, and American expansionists pursued overlapping aims."
  ], voice: { label: "The imposed treaty", excerpt: "The land cession reached communities allied with the United States as well as those it had fought.", attribution: "Treaty of Fort Jackson, 9 August 1814", sourceRef: "nps-creek" } },
  "everything-changes": { heading: "The European war releases its weight", paragraphs: [
    "Napoleon's first abdication did not cause the War of 1812, but it changed the balance within it. Britain no longer needed to direct the same concentration of troops, shipping, credit, and attention toward continental Europe. Veteran units could cross the Atlantic. The Royal Navy could intensify pressure. British negotiators could ask whether battlefield success in North America might justify territorial or strategic demands that would have been impractical during the larger emergency.",
    "Americans experienced the shift as several threats at once: operations in the Chesapeake, a major invasion through Lake Champlain, stronger forces in the Gulf, and continued pressure elsewhere. The federal government struggled to finance war after the charter of the first Bank of the United States had lapsed. Regional militia systems and state politics complicated mobilization. The capital itself remained lightly defended because leaders misjudged where and how the British would strike.",
    "Yet concentration created risks for Britain too. Long supply lines, unfamiliar waterways, disease, weather, and divided command could neutralize numerical superiority. A campaign that captured a capital might fail to produce strategic submission; a large army could retreat when its supporting fleet lost. The final year is best understood not as inevitable British escalation or inevitable American recovery, but as several high-stakes tests whose outcomes changed diplomacy."
  ], voice: { label: "News from Europe", excerpt: "Napoleon's abdication allowed British planners to treat North America as more than a secondary drain on a global war.", attribution: "British and Canadian campaign records", sourceRef: "cwm" } },
  "niagara-again": { heading: "Professionalism without decision", paragraphs: [
    "Winfield Scott's brigade trained intensely before crossing the Niagara in 1814. At Chippawa, American regulars stood in open battle and forced a British withdrawal, challenging the assumption that the army of 1812 could not meet experienced troops. Uniform color later gathered legend around the action, but drill, officers, artillery, and unit cohesion mattered more than a single visual misunderstanding.",
    "Lundy's Lane was darker, closer, and far less orderly. Units arrived in stages; guns changed hands; commanders were wounded; smoke and terrain distorted information. Both armies claimed courage and both suffered severely. The Americans left the field afterward and eventually withdrew toward Fort Erie. Calling the battle a victory for either side without explaining tactical possession, casualties, and campaign consequences substitutes a label for analysis.",
    "The campaign demonstrates the difference between battlefield competence and strategic success. The United States had improved its regular army, but it still did not secure lasting control of the Niagara peninsula. British and Canadian defense endured at high cost. Haudenosaunee communities again confronted a conflict across their homelands, sometimes limiting participation after earlier losses. Professionalization changed the fighting without resolving the political geography that produced it."
  ], voice: { label: "After-action evidence", excerpt: "Reports from Chippawa and Lundy's Lane claim performance and loss from different positions in the same confused campaign.", attribution: "British, Canadian, and American military records", sourceRef: "lac" } },
  plattsburgh: { heading: "A fleet anchors an army", paragraphs: [
    "The British invasion followed the Lake Champlain corridor, a route used in earlier imperial wars. Prévost commanded a large veteran army, but its supply depended on the waterway. On the American side, Macomb organized a smaller land defense while Macdonough prepared an anchored naval line in Plattsburgh Bay. Position partly offset British strength: attacking vessels had to enter under fire and could not easily choose a different battlefield.",
    "Macdonough planned for damage. Anchors, springs, and kedges allowed Saratoga to rotate after one broadside was battered, presenting guns from the other side. This was seamanship as preparation rather than improvisational miracle. The British flagship Confiance was powerful but newly completed, and its crew had less time to become a unit. After brutal exchanges, the British squadron struck its colors.",
    "Prévost withdrew the army. Critics later debated whether he abandoned possible land success too quickly, but without naval control his communications and resupply faced unacceptable risk. The linked result mattered at Ghent because it denied Britain leverage from a successful northern occupation. Plattsburgh therefore joins technology, geography, command judgment, and diplomacy in one compact case."
  ], voice: { label: "Prepared to turn", excerpt: "Macdonough's anchoring plan allowed Saratoga to wind and bring an unused battery into action.", attribution: "Battle of Lake Champlain records", sourceRef: "nps-plattsburgh" } },
  "washington-burns": { heading: "Capital, battlefield, and enslaved city", paragraphs: [
    "Washington was a national symbol and a small, unfinished city. Its defenses depended on uncertain intelligence, militia mobilization, and officials who disagreed about command. At Bladensburg, lines formed and broke under heat, rockets, and a rapid British advance. Joshua Barney's sailors and marines resisted near the center, but local courage could not repair the absence of coherent preparation across the whole position.",
    "The British burning targeted the Capitol, President's House, and other public buildings after American destruction in Upper Canada. That stated logic of retaliation did not make the occupation tidy. Residents fled, watched, protected property, looted, or sought opportunity amid disorder. Americans burned the Navy Yard and stores to deny them to the enemy. A storm then added physical destruction that later retellings sometimes turned into providential rescue.",
    "The familiar story of Dolley Madison saving Gilbert Stuart's Washington portrait captures one act and can obscure the labor around it. Enslaved and free servants, household staff, clerks, and laborers moved objects and sustained the city, though the archive names them unevenly. Washington was also a slaveholding capital. For enslaved residents, the arrival of British forces could mean danger, movement, intelligence work, or a possible path out of bondage."
  ], voice: { label: "The capital evacuated", excerpt: "Official correspondence and household recollections preserve different fragments of the hurried effort to remove records and possessions.", attribution: "Library of Congress War of 1812 collections", sourceRef: "loc-guide" } },
  "baltimore-holds": { heading: "A defense deeper than the fort", paragraphs: [
    "Baltimore prepared because residents had watched Washington burn and because the city already understood itself as a British target. Earthworks east of town, militia organization, harbor batteries, sunken obstructions, and thousands of laborers formed a layered system. At North Point, Stricker's force did not need to destroy the invading army to matter. By delaying it and withdrawing without disintegration, the militia bought time and delivered the British toward stronger positions.",
    "Ross's death disrupted British command, but the land force continued. From the water, bomb vessels and a rocket ship attacked Fort McHenry beyond the effective range of much American return fire. The long bombardment tested endurance more than reciprocal gunnery. A nighttime boat movement toward the harbor defenses failed to open an alternate route. With the land line formidable and the water approach closed, the expedition withdrew.",
    "The flag was both object and signal. Mary Pickersgill's household, including Grace Wisher, an African American indentured girl, made the great garrison flag on a scale requiring collective skilled labor. Francis Scott Key saw a flag in the morning and wrote the lyric that became ‘Defence of Fort M’Henry.’ Later preservation, souvenir cutting, museum care, and national-anthem adoption created additional histories after the battle itself."
  ], voice: { label: "Morning after bombardment", excerpt: "O say can you see, by the dawn's early light…", attribution: "Francis Scott Key, ‘Defence of Fort M’Henry,’ 1814", sourceRef: "nps-bombardment" } },
  "peace-at-ghent": { heading: "Negotiation is part of the war", paragraphs: [
    "The commissioners at Ghent did not negotiate outside the fighting. News of campaigns crossed the Atlantic slowly and altered what each delegation believed its government could demand. Britain initially pressed for an Indigenous buffer and territorial arrangements; American commissioners resisted concessions. European priorities, domestic politics, costs, and uncertain military prospects narrowed the distance between positions.",
    "The treaty restored conquered territory and created commissions for boundary questions. It did not secure an end to impressment in its text, even though the end of the Napoleonic wars reduced the immediate practice. Article IX promised restoration of Indigenous rights and possessions as they had stood in 1811, but Native nations were not equal parties at the table and the provision lacked the power to reverse American expansion.",
    "Signing on December 24 did not instantly end combat. The document required ratification and transatlantic transmission; forces near New Orleans still fought without reliable knowledge of the agreement. Distinguishing signature, battle, ratification, and proclamation prevents the false choice between saying the battle occurred ‘after the war’ or pretending the treaty did not exist. Historical time depended on communication and law as well as a calendar."
  ], voice: { label: "The settlement", excerpt: "All territory, places, and possessions taken during the war were to be restored, subject to the treaty's terms.", attribution: "Treaty of Ghent, 24 December 1814", sourceRef: "loc-ghent" } },
  "new-orleans": { heading: "Coalition, terrain, and later legend", paragraphs: [
    "New Orleans was a multilingual Gulf port whose population did not fit a simple national binary. Jackson's defense brought together United States regulars, Tennessee and Kentucky militia, Louisiana militia, free men of color, Choctaw fighters, sailors, marines, and Baratarian artillerists. Their legal status, motives, equipment, and treatment were unequal. Calling them all Americans may describe the command but can flatten the city's Caribbean, Indigenous, Black, and imperial histories.",
    "The campaign began before January 8. British success on Lake Borgne opened an approach; the night battle of December 23 disrupted the landing force; laborers strengthened the Rodriguez Canal line. On the decisive morning, restricted ground, mud, artillery placement, and failed British coordination exposed assaulting columns to concentrated fire. Courage existed on both sides, but tactical conditions produced radically unequal casualties.",
    "The victory arrived in American public life close to the news of peace and made Jackson a national figure. Memory often claimed the battle won the treaty, although the treaty was already signed. The more interesting relationship is political: the victory shaped how Americans interpreted an ambiguous settlement. It helped convert survival and restored borders into a story of national triumph while the contributions and later exclusion of Black and Native participants remained less secure in public memory."
  ], voice: { label: "Service and promise", excerpt: "Jackson's appeals recognized free men of color as fellow defenders during the emergency; equality did not follow after it.", attribution: "Accounts of African American service at New Orleans", sourceRef: "nps-new-orleans-black" } },
  "what-changed": { heading: "Results measured across generations", paragraphs: [
    "Peace did not distribute consequences equally. The United States gained no treaty concession on impressment and failed to conquer Canada, yet the republic survived, celebrated defensive victories, and saw the Federalist Party discredited. Manufacturing expanded under wartime scarcity. Military heroes entered electoral politics. A state could transform a negotiated restoration into a national coming-of-age story because political meaning depends on remembered sequence as well as diplomatic text.",
    "British North America remained in the empire, and defense against invasion later supplied Canadian nationalism with usable heroes. That memory should not project a unified modern nation backward. Upper and Lower Canadians, First Nations, Black militia members, British regulars, recent immigrants, and civilians experienced different obligations and risks. Britain achieved its essential defensive aim and then remembered the conflict less intensely beside the defeat of Napoleon.",
    "For Indigenous nations in the interior, the peace was profoundly unequal. Britain's negotiators abandoned the buffer-state demand, Tecumseh's coalition had lost its central leader, and American settlement accelerated. Black refugees won freedom through British lines but faced resettlement, discrimination, and hardship in Nova Scotia or the Caribbean. Rush–Bagot later reduced lake armaments, showing that governments could choose managed borders even as they failed to restore the power of peoples excluded from the settlement."
  ], voice: { label: "A demilitarized border", excerpt: "The Rush–Bagot arrangement limited naval armaments on the Great Lakes after both governments had built wartime fleets there.", attribution: "United States–British diplomatic correspondence, 1817", sourceRef: "state-rush-bagot" } }
};
