export type Source = {
  id: string;
  title: string;
  institution: string;
  url: string;
  type: string;
  note: string;
};

export type ChapterSection = {
  heading: string;
  paragraphs: string[];
  evidence?: { familiar: string; documented: string; uncertain?: string };
};

export type Chapter = {
  id: string;
  slug: string;
  order: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  date: string;
  theaters: string[];
  lede: string;
  sections: ChapterSection[];
  sourceRefs: string[];
  relatedEvents: string[];
  communities: string[];
};

export const sources: Source[] = [
  { id: "nps-war", title: "War of 1812", institution: "National Park Service", url: "https://www.nps.gov/subjects/warof1812/index.htm", type: "public-history gateway", note: "Campaigns, people, places, civilian experience, and legacies." },
  { id: "loc-guide", title: "War of 1812: A Resource Guide", institution: "Library of Congress", url: "https://guides.loc.gov/war-of-1812", type: "research guide", note: "Primary documents, maps, newspapers, prints, and manuscript collections." },
  { id: "nara-war", title: "War of 1812", institution: "National Archives", url: "https://www.archives.gov/research/military/war-of-1812", type: "archival gateway", note: "Federal military and maritime records, including impressed seamen." },
  { id: "cwm", title: "1812: One War, Four Perspectives", institution: "Canadian War Museum", url: "https://www.warmuseum.ca/war-of-1812/", type: "digital exhibition", note: "American, British, Canadian, and Indigenous interpretations shown side by side." },
  { id: "lac", title: "War of 1812 research help", institution: "Library and Archives Canada", url: "https://www.canada.ca/en/library-archives/collection/research-help/military-history/war-1812.html", type: "archive guide", note: "British, colonial, militia, and Indigenous-related records." },
  { id: "nhhc", title: "War of 1812", institution: "Naval History and Heritage Command", url: "https://www.history.navy.mil/browse-by-topic/wars-conflicts-and-operations/1812.html", type: "naval history", note: "Atlantic, lake, Chesapeake, and Pacific naval operations." },
  { id: "house-declaration", title: "War of 1812 Declaration", institution: "U.S. House of Representatives", url: "https://history.house.gov/Records-and-Research/Listing/lfp_012/", type: "primary document guide", note: "The declaration and congressional context." },
  { id: "nara-impressment", title: "Records About Impressed Seamen, 1793–1814", institution: "National Archives", url: "https://www.archives.gov/research/military/war-of-1812/1812-discharge-certificates/impressed-seamen-1793-to-1814", type: "archival collection", note: "Protection certificates and records of maritime identity." },
  { id: "nps-riots", title: "Baltimore Residents Riot Against Antiwar Dissenters", institution: "National Park Service", url: "https://www.nps.gov/articles/baltimore-riots.htm", type: "public history", note: "The June and July 1812 attacks on the Federal Republican and its defenders." },
  { id: "bca", title: "The War of 1812 in Baltimore", institution: "Baltimore City Archives", url: "https://msa.maryland.gov/bca/war-of-1812-in-baltimore/", type: "local archive", note: "Municipal records and Baltimore source material." },
  { id: "nps-indigenous", title: "Indigenous Peoples and the War of 1812", institution: "National Park Service", url: "https://home.nps.gov/subjects/warof1812/indigenous-peoples.htm", type: "public history", note: "Indigenous objectives, coalitions, campaigns, and consequences." },
  { id: "parks-pierpoint", title: "Richard Pierpoint", institution: "Parks Canada", url: "https://parks.canada.ca/culture/designation/personnage-person/richard-pierpoint", type: "biographical record", note: "Black Loyalist veteran and Upper Canadian militia organizer." },
  { id: "parks-black-militia", title: "Black Militia Units in Upper Canada", institution: "Parks Canada", url: "https://parks.canada.ca/culture/designation/evenement-event/unites-milice-noirs-black-militia-units", type: "historic designation", note: "Black service in Upper Canada." },
  { id: "nps-lake-erie", title: "Battle of Lake Erie", institution: "National Park Service", url: "https://home.nps.gov/pevi/learn/historyculture/battle_erie_detail.htm", type: "battle study", note: "Perry's victory and its operational consequences." },
  { id: "nhhc-pacific", title: "The War in the Pacific, 1813–April 1814", institution: "Naval History and Heritage Command", url: "https://www.history.navy.mil/our-collections/art/travelling-exhibits/the-war-of-1812/the-war-in-the-pacific--1813-april-1814-.html", type: "digital exhibition", note: "USS Essex, Pacific prizes, Nuku Hiva, and Valparaíso." },
  { id: "nps-living", title: "Living Through Conflict Narratives", institution: "National Park Service", url: "https://www.nps.gov/subjects/warof1812/living-conflict-narratives.htm", type: "civilian history", note: "Civilian experiences of invasion, occupation, and displacement." },
  { id: "nps-freedom-1", title: "Black Freedom Seeking During the War of 1812, Part 1", institution: "National Park Service", url: "https://www.nps.gov/articles/000/black-freedom-seeking-during-the-war-of-1812-from-the-chesapeake-cumberland-island-and-beyond-part-1.htm", type: "public history", note: "Freedom seekers from the Chesapeake to Cumberland Island." },
  { id: "nps-colonial", title: "Freedom Seekers and the Colonial Marines", institution: "National Park Service", url: "https://home.nps.gov/stsp/learn/historyculture/colonial-marines.htm", type: "public history", note: "British emancipation strategy and the Corps of Colonial Marines." },
  { id: "nps-creek", title: "Creek War in the Southeast", institution: "National Park Service", url: "https://www.nps.gov/articles/creek-war-in-the-southeast-1.htm", type: "campaign overview", note: "Muscogee civil conflict, United States intervention, and regional expansion." },
  { id: "nps-prince-witten", title: "Sanctuary in the Spanish Empire: Prince Witten", institution: "National Park Service", url: "https://www.nps.gov/articles/sanctuary-in-the-spanish-empire.htm", type: "biographical study", note: "Spanish Florida, the Patriot War, Black militia, and freedom seeking." },
  { id: "nps-plattsburgh", title: "Battle of Lake Champlain", institution: "National Park Service", url: "https://www.nps.gov/articles/battle-of-lake-champlain.htm", type: "battle study", note: "Macdonough's victory and Prévost's withdrawal." },
  { id: "nhhc-flotilla", title: "Chesapeake Flotilla", institution: "Naval History and Heritage Command", url: "https://www.history.navy.mil/research/underwater-archaeology/sites-and-projects/ship-wrecksites/chesapeakeflotilla1812.html", type: "archaeology and naval history", note: "Joshua Barney's flotilla and the Washington campaign." },
  { id: "nps-baltimore", title: "Battle for Baltimore City", institution: "National Park Service", url: "https://www.nps.gov/stsp/learn/historyculture/battle-for-baltimore-city.htm", type: "campaign overview", note: "The land and water defenses of Baltimore." },
  { id: "nps-north-point", title: "Battle of North Point", institution: "National Park Service", url: "https://www.nps.gov/stsp/learn/historyculture/battle-of-north-point.htm", type: "battle study", note: "Ross, Stricker, and the delaying action outside Baltimore." },
  { id: "nps-bombardment", title: "The Bombardment of Fort McHenry", institution: "National Park Service", url: "https://home.nps.gov/fomc/learn/historyculture/the-bombardment-of-fort-mchenry.htm", type: "battle study", note: "Fort McHenry and Baltimore's harbor defenses." },
  { id: "nps-grace", title: "Grace Wisher", institution: "National Park Service", url: "https://www.nps.gov/fomc/learn/historyculture/grace-wisher.htm", type: "biographical study", note: "The African American indentured girl who worked in Mary Pickersgill's household as the great flag was made." },
  { id: "smithsonian-flag", title: "The Star-Spangled Banner", institution: "Smithsonian National Museum of American History", url: "https://americanhistory.si.edu/collections/object/nmah_463144", type: "object record", note: "Object history, dimensions, material, and conservation." },
  { id: "loc-ghent", title: "Treaty of Ghent: Primary Documents in American History", institution: "Library of Congress", url: "https://guides.loc.gov/treaty-of-ghent", type: "primary-source guide", note: "Treaty text, negotiations, and related documents." },
  { id: "nps-new-orleans-black", title: "Accounts of African American Service", institution: "National Park Service", url: "https://www.nps.gov/articles/accounts-of-african-american-service-during-the-war-of-1812.htm", type: "public history", note: "Free Black units and Black military service, including New Orleans." },
  { id: "nps-choctaw", title: "Choctaw Recruits Fight with the U.S. Army", institution: "National Park Service", url: "https://home.nps.gov/articles/choctaw-indians-and-the-battle-of-new-orleans.htm", type: "public history", note: "Choctaw participation in the New Orleans campaign." },
  { id: "lafolklife", title: "Stories Told About the Nineteenth-Century Filipino Settlement at St. Malo", institution: "Louisiana Folklife Program", url: "https://www.louisianafolklife.org/LT/Articles_Essays/lfmStMalo.html", type: "folklore and historiography", note: "Separates documentation, community tradition, and later retelling." },
  { id: "nps-legacies", title: "Legacies of the War of 1812", institution: "National Park Service", url: "https://www.nps.gov/subjects/warof1812/legacies-of-the-war-of-1812.htm", type: "public history", note: "Postwar political, diplomatic, cultural, and social consequences." },
  { id: "state-rush-bagot", title: "Rush–Bagot Pact and Convention of 1818", institution: "Office of the Historian, U.S. Department of State", url: "https://history.state.gov/milestones/1801-1829/rush-bagot", type: "diplomatic history", note: "Border settlement and demilitarization after the war." },
  { id: "loc-fort-print", title: "A View of the Bombardment of Fort McHenry", institution: "Library of Congress", url: "https://www.loc.gov/pictures/item/2013645001/", type: "image record", note: "John Bower, approximately 1819; LOC states no known restrictions on publication." },
];

export const chapters: Chapter[] = [
  {
    id: "prologue", slug: "world-already-at-war", order: 0, eyebrow: "Prologue · 1803–1811", title: "A World Already at War", subtitle: "The neutral republic, the global struggle, and the road to 1812", date: "1803–1811", theaters: ["Atlantic", "Old Northwest", "Politics"],
    lede: "The War of 1812 began long before anyone declared it. Britain and France were fighting for Europe, the Atlantic, and the commerce that connected them. The United States tried to remain neutral and profitable. Every part of that arrangement became unstable.",
    sections: [
      { heading: "A republic between empires", paragraphs: ["When war resumed between Britain and Napoleonic France in 1803, American merchants entered the spaces opened by belligerents who could no longer trade normally. Neutral commerce enriched port cities and enlarged the American merchant fleet. It also placed American ships directly inside an imperial contest in which neither London nor Paris accepted neutral rights when those rights helped the enemy.", "Britain commanded the sea after Trafalgar. France tried to close European ports to British goods; Britain answered with Orders in Council restricting trade with Napoleonic Europe. American vessels were stopped, searched, diverted, seized, or condemned. The conflict did not remain an abstract argument about international law. It reached every sailor whose identity an officer disputed and every merchant whose voyage could end in a prize court." ] },
      { heading: "Who was an American sailor?", paragraphs: ["The Royal Navy needed men on a scale the peacetime United States scarcely understood. British officers claimed a right to recover deserters and British subjects from neutral vessels. In practice, documentary identity at sea was porous, protection papers could be doubted, and naturalization meant less to British officers than it did to Americans. Thousands of sailors were impressed; some were British, some American, and many occupied the contested ground between those categories.", "The 1807 Chesapeake–Leopard affair made the insult spectacular. HMS Leopard fired into USS Chesapeake after its commander refused a search for deserters. Americans saw a national warship humiliated almost within sight of home. Thomas Jefferson answered with embargo rather than war. The embargo damaged American commerce and intensified domestic division without compelling Britain or France to respect American claims." ] },
      { heading: "The other frontier", paragraphs: ["At the same time, American settlement pressed into Indigenous homelands in the Old Northwest. Tecumseh and Tenskwatawa worked to build a coalition able to resist piecemeal land cessions. British officials in North America saw Indigenous alliances as strategically useful; Indigenous leaders saw British support as one possible means of defending land and political autonomy. Those motives overlapped, but they were never identical.", "William Henry Harrison's forces fought at Tippecanoe in November 1811 while Tecumseh was away recruiting support. Americans used the battle as evidence of British intrigue. For many Native communities, the deeper cause was not British manipulation but American expansion. By 1812, maritime coercion, partisan politics, national honor, commercial injury, and a continental struggle over land had become one crisis." ] }
    ], sourceRefs: ["nara-impressment", "loc-guide", "nps-indigenous", "cwm"], relatedEvents: ["chesapeake-leopard", "tippecanoe"], communities: ["American seafarers", "British sailors", "Tecumseh's coalition", "frontier settlers"]
  },
  {
    id: "ch-01", slug: "why-war", order: 1, eyebrow: "Chapter 1 · June 1812", title: "Why War?", subtitle: "A divided republic chooses a dangerous remedy", date: "June 1812", theaters: ["Politics", "Atlantic", "Old Northwest"],
    lede: "The United States did not go to war for one reason, and it did not go united. Congress chose war by the narrowest votes yet cast for such a decision. The causes were connected precisely because Americans disagreed over which injury mattered most.",
    sections: [
      { heading: "Madison's case", paragraphs: ["President James Madison's war message assembled a bill of grievances: impressment, interference with commerce, violation of American waters, and British encouragement of Indigenous resistance. It did not openly demand Canada. Yet invasion of British North America became the immediate military strategy, partly because the United States could not challenge the Royal Navy on equal terms and partly because some War Hawks imagined Canada as leverage—or opportunity.", "News traveled more slowly than policy changed. Britain moved to suspend the Orders in Council shortly before the American declaration, but the decision could not cross the Atlantic in time to stop Congress. Even if it had, impressment and western conflict remained unresolved. The timing sharpened the war's tragic quality without making its causes disappear." ] },
      { heading: "A nation voting by section", paragraphs: ["The House approved war 79–49; the Senate followed 19–13. Democratic-Republican strength in the South and West carried the decision. Federalists and many representatives from commercial New England opposed it. The vote was not a referendum on whether British policy was objectionable; it was a judgment about whether war was the proper, affordable, constitutional, and strategically sane response.", "The opposition predicted commercial ruin and military embarrassment. Supporters answered that a republic unable to defend its citizens, ships, and borders was independent in name only. Both sides invoked the Revolution. Neither possessed a reliable plan for the war that followed." ] },
      { heading: "The first battlefield is political", paragraphs: ["Madison signed the declaration on June 18. Mobilization exposed every weakness in the American system: a tiny regular army, short enlistments, state militias with contested obligations, unreliable finance, and senior officers chosen as much for Revolutionary pedigree as current fitness. The government expected pressure on Canada to force British concessions. It underestimated distance, logistics, command failure, Indigenous power, and Canadian resistance.", "Before those errors became visible at Detroit or Queenston Heights, Baltimore supplied the first proof that war could reorder civic life. Four days after the declaration, a crowd moved against the newspaper that had condemned it." ] }
    ], sourceRefs: ["house-declaration", "loc-guide", "nara-war", "cwm"], relatedEvents: ["war-declaration", "baltimore-riot-june"], communities: ["Democratic-Republicans", "Federalists", "maritime workers", "western settlers"]
  },
  {
    id: "ch-02", slug: "baltimore-at-war-with-itself", order: 2, eyebrow: "Chapter 2 · June–July 1812", title: "Baltimore I: A City at War With Itself", subtitle: "A press destroyed, a jail invaded, and a Revolutionary general murdered", date: "22 June–28 July 1812", theaters: ["Chesapeake", "Politics", "Civilian"],
    lede: "Two years before British troops marched toward Baltimore, the city had already shown how much violence the war could produce without a redcoat in sight.",
    sections: [
      { heading: "The press", paragraphs: ["Alexander Contee Hanson's Federal Republican opposed the war with a ferocity suited to Baltimore's equally ferocious politics. On June 22, a pro-war crowd attacked the newspaper office and destroyed the press. Officials did not restore order so much as watch it arrive after the damage was done.", "Hanson refused to disappear. He gathered armed supporters, including Revolutionary War veterans James M. Lingan and Henry “Light-Horse Harry” Lee, and resumed publication from a house on Charles Street. On the night of July 27, a crowd surrounded the building. Gunfire left attackers dead and wounded. The defenders surrendered to civil authorities after receiving assurances of protection." ] },
      { heading: "The jail", paragraphs: ["The authorities moved the Federalists to the city jail, supposedly for safety. The next night a mob forced its way inside. It tortured and beat the prisoners. Lingan—an officer captured at Fort Washington during the Revolution and held on the British prison ship Jersey—was killed by fellow Americans. Lee, father of the future Confederate general, suffered injuries from which he never fully recovered. Hanson and others were mutilated and left for dead.", "This was not Americans nearly killing one another over the war. They killed Lingan. The distinction matters because euphemism turns political violence into atmosphere. Maryland investigations condemned failures of authority, while partisan accounts disputed responsibility and sequence. The essential fact remained: the city government had failed to protect prisoners placed in its custody." ] },
      { heading: "A bookend, not a detour", paragraphs: ["The riots make the later defense of Baltimore more consequential, not less. In 1814 the city would mobilize labor, money, militia, sailors, free Black residents, enslaved workers, merchants, artisans, and federal forces behind earthworks and batteries. That unity was contingent, created under threat, and layered over unresolved political division.", "Baltimore's two wartime moments belong together. In 1812 the question was whether the city could survive itself. In 1814 it would be whether the city could survive the British Empire." ] }
    ], sourceRefs: ["nps-riots", "bca", "nps-baltimore"], relatedEvents: ["baltimore-riot-june", "baltimore-jail-massacre"], communities: ["Federalists", "Democratic-Republicans", "Baltimore printers", "Revolutionary veterans"]
  },
  {
    id: "ch-03", slug: "easy-conquest-that-wasnt", order: 3, eyebrow: "Chapter 3 · 1812", title: "The Easy Conquest That Wasn’t", subtitle: "Detroit, Queenston Heights, and the collapse of American assumptions", date: "July–October 1812", theaters: ["Great Lakes", "Upper Canada", "Old Northwest"],
    lede: "American strategy treated British North America as the pressure point. It became the place where confidence met geography, divided command, weak supply, and an alliance the United States badly misunderstood.",
    sections: [
      { heading: "Three invasions, no system", paragraphs: ["The American plan imagined advances across a vast border as though they were parts of one operation. They were not. Roads failed, supplies vanished, militia terms expired, commanders protected their own departments, and messages moved too slowly. An army that looked adequate on a return could become hungry and isolated after a few marches.", "Brigadier General William Hull crossed from Detroit into Upper Canada and issued a proclamation promising protection to inhabitants who did not resist. He also threatened those who fought alongside Indigenous warriors. The language exposed the American assumption that Canadians would welcome—or at least accept—an invasion and that Native resistance was illegitimate." ] },
      { heading: "Brock and Tecumseh", paragraphs: ["Major General Isaac Brock and Tecumseh recognized Hull's uncertainty. Their alliance was practical and uneasy: Brock needed Indigenous strength; Tecumseh needed British material and a barrier against American expansion. At Detroit they used movement, reputation, and deception to magnify their numbers. Hull surrendered the fort and an army on August 16 without enduring an assault.", "The victory preserved Upper Canada at its most vulnerable moment and armed Indigenous forces with captured supplies. It also made Brock and Tecumseh symbols in later national memories that can obscure their different political aims. Brock defended British territory. Tecumseh fought for a Native political future that Britain would later fail to secure." ] },
      { heading: "Queenston Heights", paragraphs: ["At Queenston Heights in October, American regulars and militia crossed the Niagara River and gained ground. Brock was killed leading a counterattack. But reinforcements on the American bank refused to cross, citing militia limits and fear of Indigenous warriors. British, Canadian, and Indigenous forces retook the heights; hundreds of Americans surrendered.", "By winter, the supposed lever of Canada had become a catalogue of American institutional weakness. Yet the failures did not end the invasion strategy. They ensured that the struggle for the border, the lakes, and the shipyards would grow larger." ] }
    ], sourceRefs: ["cwm", "lac", "parks-pierpoint", "nps-indigenous"], relatedEvents: ["detroit-surrender", "queenston-heights"], communities: ["British regulars", "Upper Canadian militia", "Tecumseh's coalition", "American regulars and militia"]
  },
  {
    id: "ch-04", slug: "old-ironsides", order: 4, eyebrow: "Chapter 4 · 1812–1813", title: "“Old Ironsides” and the War at Sea", subtitle: "Tactical brilliance beneath British oceanic supremacy", date: "August 1812–June 1813", theaters: ["Atlantic", "Naval"],
    lede: "The Royal Navy ruled the oceans. American frigates could not change that fact. But a handful of ship-to-ship victories changed how Americans imagined the war—and how the Royal Navy treated its opponent.",
    sections: [
      { heading: "A few very large frigates", paragraphs: ["USS Constitution, United States, and their sisters carried heavy guns, large crews, and robust scantlings. They were not magical ships, and they did not win alone: training, gunnery, command, weather, and the condition of opponents mattered. But American designers had produced frigates able to overpower typical British ships of the same nominal class while escaping ships of the line.", "Constitution's defeat of HMS Guerriere in August 1812 supplied the war with an immediate legend. Shots reportedly appeared to rebound from Constitution's sides, encouraging the name “Old Ironsides.” United States captured HMS Macedonian in October; Constitution destroyed HMS Java in December. Prizes, trophies, and dispatches reached a public hungry for competence after disaster in Canada." ] },
      { heading: "Victory, scale, and race", paragraphs: ["These duels did not break blockade or threaten British command of the sea. The Admiralty soon directed captains to avoid unequal single-ship contests. The larger strategic balance became harsher for the United States as more British squadrons arrived.", "American crews were not racially uniform. Free Black sailors and some enslaved men served in naval and privateering crews, where maritime labor, coercion, prize money, patriotism, and the possibility of mobility intersected. Their service complicates any clean contrast between an American language of liberty and a British empire that would later offer freedom to people escaping American slavery." ] },
      { heading: "The other side of the legend", paragraphs: ["In June 1813, HMS Shannon defeated USS Chesapeake outside Boston. Captain James Lawrence's dying command not to give up the ship outlived the lost ship itself. That reversal reveals how naval memory works: a phrase, a flag, or a battered hull can detach from the tactical result and become national property.", "Privateers extended the maritime war through hundreds of commercial ventures. They captured merchantmen, disrupted trade, enriched some investors, and forced Britain to spend resources on convoy and protection. They also depended on courts, capital, intelligence, and multinational labor—not simply daring captains." ] }
    ], sourceRefs: ["nhhc", "nara-war", "loc-guide"], relatedEvents: ["constitution-guerriere", "united-states-macedonian", "chesapeake-shannon"], communities: ["U.S. Navy sailors", "Royal Navy sailors", "Black mariners", "privateers"]
  },
  {
    id: "ch-05", slug: "war-for-the-interior", order: 5, eyebrow: "Chapter 5 · 1813", title: "The War for the Interior", subtitle: "Lake Erie, the Thames, and the breaking of a coalition", date: "January–October 1813", theaters: ["Old Northwest", "Great Lakes", "Indigenous homelands"],
    lede: "The struggle in the interior was not merely a frontier attached to an Anglo-American war. It was a contest over whether Native nations could prevent the United States from converting military roads and treaties into permanent territorial control.",
    sections: [
      { heading: "Holding the line", paragraphs: ["Tecumseh's coalition survived the victory at Detroit but depended on British supplies and continued military commitment. American forces returned under William Henry Harrison. At the River Raisin, Fort Meigs, and Fort Stephenson, campaigning mixed siege, hunger, raids, prisoner crises, and cycles of retaliation. Communities experienced the war as a threat to food, shelter, and political survival.", "British officers and Native leaders argued over strategy because they bore different risks. A British withdrawal might sacrifice territory. For Native communities it could expose homes and families. Alliance did not erase asymmetry." ] },
      { heading: "We have met the enemy", paragraphs: ["On Lake Erie, both sides built fleets from timber, transported cannon and rigging over primitive routes, and competed for sailors. Oliver Hazard Perry defeated Robert Barclay's squadron on September 10, 1813. Perry's brief dispatch became famous; the strategic consequence mattered more. Control of the lake severed British supply and forced a retreat from Detroit.", "Harrison followed. At the Battle of the Thames on October 5, British resistance collapsed and Tecumseh was killed. The circumstances of his death and the fate of his remains generated rival claims and later legend. The political result was less ambiguous: the coalition lost an irreplaceable leader, and British capacity to support a Native barrier in the region diminished." ] },
      { heading: "A victory that belonged differently", paragraphs: ["Americans celebrated the recovery of Detroit and destruction of British power in the region. For participating Native nations, the campaign marked a profound loss of leverage. Yet “Indigenous defeat” cannot stand as a single experience. Nations, towns, families, and leaders had made different alliances and would face different treaties and removals.", "The peace settlement would nominally call for restoration of Native rights and possessions as they stood before the war. It supplied no enforcement mechanism and no independent seat at the table. The war for the interior did not end cleanly in 1813; its consequences stretched across decades of American expansion." ] }
    ], sourceRefs: ["nps-indigenous", "nps-lake-erie", "lac"], relatedEvents: ["lake-erie", "battle-thames"], communities: ["Tecumseh's coalition", "British regulars", "American Northwest Army", "Great Lakes shipbuilders"]
  },
  {
    id: "ch-06", slug: "continental-naval-arms-race", order: 6, eyebrow: "Chapter 6 · 1812–1814", title: "Lakes, Shipyards, and a Continental Naval Arms Race", subtitle: "The fleets built where roads did not exist", date: "1812–1814", theaters: ["Great Lakes", "Lake Champlain", "Logistics"],
    lede: "Some of the largest warships on the continent were built in inland shipyards because whoever controlled the lakes controlled the roads that did not exist.",
    sections: [
      { heading: "Water as infrastructure", paragraphs: ["North American campaigns were governed by movement. An army consumed food, fodder, powder, clothing, medicine, and replacements every day. Overland transport was slow and ruinously expensive. Lakes and rivers could carry weight at a scale roads could not. A fleet therefore did more than fight another fleet: it kept an army possible.", "At Sackets Harbor and Kingston, laborers transformed frontier ports into strategic industrial complexes. Shipwrights, sailors, soldiers, merchants, teamsters, and timber cutters drew material from widening hinterlands. Cannon and anchors came from far away. Disease and accidents killed without appearing in battle lists." ] },
      { heading: "Lake Ontario's strange equilibrium", paragraphs: ["On Lake Ontario, Commodore Isaac Chauncey and Sir James Yeo pursued an arms race in which each new vessel could make the existing fleet temporarily obsolete. Both commanders protected their squadrons because losing control could expose an entire theater. The result was not constant decisive battle but maneuver, convoy, raids, blockade, and frantic construction.", "The giant ships symbolize both ingenuity and strategic absurdity: oceanic naval architecture recreated inland, at enormous expense, to dominate a body of water from which the vessels could never sail to sea." ] },
      { heading: "Three lakes, three wars", paragraphs: ["Lake Erie produced a decisive American victory tied directly to a land campaign. Lake Ontario remained contested and constrained operations on both sides. Lake Champlain would decide whether a major British invasion in 1814 could remain supplied. Treating “the war on the lakes” as one story hides these different strategic systems.", "The shipyards also make the war social. Forests became naval stores; farms became supply bases; civilian labor became military capacity. The water war was won or lost long before cannon fire, in procurement, transport, carpentry, and the ability to keep thousands of people fed." ] }
    ], sourceRefs: ["lac", "nhhc", "nps-lake-erie"], relatedEvents: ["sackets-harbor", "lake-erie", "lake-champlain"], communities: ["shipwrights", "naval artificers", "Great Lakes sailors", "civilian suppliers"]
  },
  {
    id: "ch-07", slug: "war-around-cape-horn", order: 7, eyebrow: "Chapter 7 · 1813–1814", title: "The War Goes Around Cape Horn", subtitle: "USS Essex carries the conflict into the Pacific", date: "1813–1814", theaters: ["Pacific", "Naval", "Polynesia"],
    lede: "The familiar map of the war stops at the Atlantic coast. David Porter's USS Essex did not. It rounded Cape Horn and turned an Anglo-American conflict into a Pacific war touching South America, the Galápagos, and the Marquesas.",
    sections: [
      { heading: "A commerce war in another ocean", paragraphs: ["Porter entered the Pacific to attack British commerce, especially the whaling fleet that supplied oil, wealth, and trained mariners. Essex captured prizes and built a small improvised squadron. The cruise demonstrated how a single frigate, beyond the immediate reach of a superior navy, could disrupt an industry across immense distances.", "Prize crews reduced Porter's available manpower even as captures multiplied. Neutral ports, uncertain intelligence, maintenance, and the need for supplies constrained every choice. The Pacific magnified the logistical problems visible everywhere else in the war." ] },
      { heading: "Nuku Hiva", paragraphs: ["At Nuku Hiva in the Marquesas, Porter refitted, established a base, intervened in local conflicts, and claimed an island for the United States. The claim had no durable legal effect. More important, the episode must not be narrated as an empty island awaiting an American flag. Polynesian communities possessed their own rivalries, diplomacy, authority, and interpretations of the newcomers.", "American accounts framed violence through their own categories and purposes. Reading them critically means treating Indigenous Pacific peoples as historical actors rather than scenery in an American adventure." ] },
      { heading: "Valparaíso", paragraphs: ["HMS Phoebe and HMS Cherub eventually trapped Essex at Valparaíso. On March 28, 1814, after a squall damaged his ship, Porter attempted escape and then fought a destructive action within sight of the neutral coast. Essex surrendered after heavy casualties.", "The cruise did not change control of the Pacific. It did reveal the war's global reach, the economic geography of whaling, and the distance between a tactical raider's success and strategic naval power. A war can be global even when most textbooks draw a small map." ] }
    ], sourceRefs: ["nhhc-pacific", "nhhc"], relatedEvents: ["essex-pacific", "nuku-hiva", "valparaiso"], communities: ["American sailors", "British whalers", "Marquesan communities", "Chilean port residents"]
  },
  {
    id: "ch-08", slug: "war-reaches-homes", order: 8, eyebrow: "Chapter 8 · 1813", title: "The War Reaches Towns and Homes", subtitle: "Occupation, burning, flight, and retaliation", date: "April–December 1813", theaters: ["Upper Canada", "Niagara", "Chesapeake", "Civilian"],
    lede: "Campaign maps turn towns into names and arrows. In 1813 the war became a sequence of people deciding whether to flee, hide property, cooperate, resist, or gamble that uniforms would pass them by.",
    sections: [
      { heading: "York and retaliation", paragraphs: ["American forces captured York, the capital of Upper Canada, in April. The fighting killed Brigadier General Zebulon Pike. American troops looted buildings and burned the parliament house and other property. Commanders later argued over responsibility and military purpose. Civilians experienced the distinction between authorized destruction and indiscipline less neatly.", "Later British destruction in Washington was often explained as retaliation for York and other Canadian burnings. Retaliation was part of British justification, but simple chains of vengeance can conceal strategic choice. Each act had its own targets, orders, opportunities, and politics." ] },
      { heading: "Niagara", paragraphs: ["The Niagara frontier changed hands repeatedly. Fort George fell; American forces advanced and stalled; British and allied forces recovered initiative. In December, retreating Americans burned Newark, forcing inhabitants into winter cold. British forces answered across the river at Buffalo and Black Rock.", "Military occupation rearranged everyday power. Residents dealt with requisitions, billeting, suspected disloyalty, missing livestock, damaged mills, and the danger of being identified with whichever side had just left." ] },
      { heading: "The Chesapeake becomes a front", paragraphs: ["British raids struck Havre de Grace, Georgetown, Frenchtown, and communities along the bay. At St. Michaels, residents and militia defended a shipbuilding town; later memory embroidered the episode with stories of lanterns moved into trees. Hampton experienced looting and violence after its capture. The record demands care because atrocity claims became wartime propaganda as well as testimony.", "For enslaved people, the arrival of British ships could create a narrow and dangerous opening. Escape risked family separation, retaliation, recapture, and an unknown future. Remaining was not consent to slavery; leaving was not a simple choice made without coercion. These decisions belong at the center of campaign history because local knowledge, labor, and movement shaped operations." ] }
    ], sourceRefs: ["nps-living", "nps-freedom-1", "nps-war", "cwm"], relatedEvents: ["york", "havre-de-grace", "st-michaels", "burning-newark"], communities: ["Upper Canadian civilians", "Chesapeake civilians", "enslaved families", "women and children"]
  },
  {
    id: "ch-09", slug: "blockade", order: 9, eyebrow: "Chapter 9 · 1813–1814", title: "Blockade", subtitle: "How the Royal Navy made ordinary trade impossible", date: "1813–1814", theaters: ["Atlantic", "Chesapeake", "Economy"],
    lede: "The blockade rarely supplies a single heroic scene. It changed the war by narrowing thousands of ordinary possibilities: whether a ship could sail, whether a crop could reach market, whether credit would hold, whether a coastal town slept.",
    sections: [
      { heading: "Pressure by degrees", paragraphs: ["Britain tightened the blockade over time. New England initially received different treatment in hopes of exploiting regional opposition to the war, while the Chesapeake became a base for increasingly aggressive operations. By 1814 the system pressed much of the coast, backed by a navy able to replace ships and men on a scale the United States could not match.", "Blockade meant capture risk, higher insurance, idle vessels, unemployment, scarce imports, and falling customs revenue for a federal government that depended heavily on trade. It also encouraged smuggling and bargaining across supposedly hostile lines." ] },
      { heading: "Private war, public consequences", paragraphs: ["American privateers captured British merchantmen and complicated insurance and convoying. Their successes were real. So was their inability to reopen American ports. A privateer could make a profitable cruise while the national economy contracted.", "The distinction between navy, commerce, and private investment blurred. Merchants financed armed ships; courts translated captures into title; newspapers advertised prizes; sailors weighed wages against shares. The maritime war ran through legal and financial institutions as well as gun decks." ] },
      { heading: "The coast under observation", paragraphs: ["British squadrons used the Chesapeake as an operational space, collecting intelligence, water, provisions, pilots, and escapees from slavery. Local residents watched sails and signal stations, moved valuables, drilled militia, and negotiated when armed boats entered creeks.", "The blockade prepared the invasions of 1814. It mapped channels, tested defenses, cultivated knowledge, and forced the United States to spread limited forces across a long coastline. By the time troops landed for Washington, the bay had already been at war for more than a year." ] }
    ], sourceRefs: ["nhhc", "nhhc-flotilla", "nps-freedom-1"], relatedEvents: ["chesapeake-blockade", "cochrane-proclamation"], communities: ["merchants", "privateers", "coastal residents", "freedom seekers"]
  },
  {
    id: "ch-10", slug: "southern-borderlands", order: 10, eyebrow: "Chapter 10 · 1812–1814", title: "The Southern Borderlands", subtitle: "Creek War, Spanish Florida, and competing freedoms", date: "1812–1814", theaters: ["Gulf", "Muscogee homelands", "Spanish Florida"],
    lede: "In the South, the Anglo-American war overlapped with Muscogee civil conflict, Spanish imperial rule, American filibustering, slavery, and competing geographies of refuge. Andrew Jackson was not the beginning of this story.",
    sections: [
      { heading: "A civil war Americans entered", paragraphs: ["Muscogee communities disagreed over accommodation, land, trade, religious renewal, and the growing power of the United States. Red Stick resistance emerged from this political world. Other Muscogee leaders, along with Cherokee and Choctaw fighters, allied with American forces for reasons of their own. “Creek versus American” is therefore as misleading as treating Native nations elsewhere as a single British auxiliary.", "The attack on Fort Mims in August 1813 killed hundreds and galvanized American mobilization. Retellings often isolate its violence from the wider civil war and the campaigns that followed. American and allied forces destroyed towns and food supplies, turning military defeat into a humanitarian catastrophe." ] },
      { heading: "Horseshoe Bend", paragraphs: ["At Horseshoe Bend in March 1814, Jackson's army, including Cherokee and Lower Creek allies, broke Red Stick defenses. Menawa survived despite severe wounds. The battle ended organized resistance in that campaign but not the region's conflicts.", "The Treaty of Fort Jackson compelled a cession of roughly 23 million acres from the Muscogee Confederacy, including land belonging to communities that had fought alongside the United States. Jackson treated the cession as security and indemnity. Its reach showed how an alliance could end in dispossession." ] },
      { heading: "Florida was not empty", paragraphs: ["Spanish Florida offered sanctuary and strategic ambiguity. American-backed Patriots attempted to seize East Florida; U.S. forces crossed boundaries; Spanish officials, Native communities, enslaved people, freedom seekers, and free Black militia navigated overlapping claims. Prince Witten's life illuminates a world in which Spanish allegiance and military service could offer possibilities unavailable under American racial slavery.", "In West Florida and Pensacola, British activity, Spanish weakness, and American expansion converged. These were not peripheral complications. They connected the Creek War to New Orleans and helped produce later conflict against Seminole and Black communities." ] }
    ], sourceRefs: ["nps-creek", "nps-prince-witten", "nps-indigenous"], relatedEvents: ["fort-mims", "horseshoe-bend", "treaty-fort-jackson", "pensacola"], communities: ["Red Stick Muscogee", "Lower Creek allies", "Cherokee fighters", "Spanish Florida's Black militia"]
  },
  {
    id: "ch-11", slug: "everything-changes", order: 11, eyebrow: "Chapter 11 · 1814", title: "Everything Changes", subtitle: "Napoleon falls, veterans cross the Atlantic, and the war grows more dangerous", date: "Spring–Summer 1814", theaters: ["Atlantic world", "United States", "British North America"],
    lede: "For two years, Britain's war against Napoleon limited what it could send to North America. Napoleon's first abdication in April 1814 did not make Britain omnipotent. It made the American war newly worth resources.",
    sections: [
      { heading: "A secondary war becomes available", paragraphs: ["British strategic priorities had never been mysterious. France threatened the balance of Europe and the British state; the United States did not. With troops released from the Peninsula and Atlantic pressure eased, Britain could reinforce North America, intensify blockade, raid the American coast, and launch coordinated offensives.", "The purpose was not necessarily wholesale conquest. British planners sought leverage, security for Canada, possible territorial adjustments, and punishment sufficient to produce acceptable peace. Objectives shifted with military news and political opportunity." ] },
      { heading: "A better American army", paragraphs: ["The United States was also learning. Jacob Brown and Winfield Scott imposed stricter training and field discipline on regular formations along the Niagara. Staff work and tactical performance improved. The army of 1814 was not the army that Hull surrendered at Detroit.", "Improvement did not solve finance, strategic coordination, or the vulnerability of the coast. The paradox of 1814 is that American regulars fought better at the same moment the national position became more dangerous." ] },
      { heading: "Several invasions at once", paragraphs: ["British power threatened the Niagara frontier, Lake Champlain corridor, Chesapeake, and Gulf. These were not movements on a single battlefield. Each depended on its own supply system and local command, but together they forced the United States to guess where limited resources mattered most.", "The decisive American defensive story would not emerge from one commander or one city. It would come from separate contests at Plattsburgh, Washington, Baltimore, and New Orleans—some victories, one spectacular humiliation, and each with a different relationship to peace." ] }
    ], sourceRefs: ["nps-war", "cwm", "lac"], relatedEvents: ["napoleon-abdication", "chippawa", "british-chesapeake-campaign"], communities: ["Peninsular veterans", "American regulars", "Canadian militia", "coastal civilians"]
  },
  {
    id: "ch-12", slug: "niagara-again", order: 12, eyebrow: "Chapter 12 · July–November 1814", title: "Niagara, Again", subtitle: "Better armies, terrible casualties, and no strategic decision", date: "July–November 1814", theaters: ["Niagara", "Upper Canada"],
    lede: "The Niagara campaign proved the American army could stand against British regulars. It also proved that tactical competence could consume thousands of lives without producing the conquest strategy had promised.",
    sections: [
      { heading: "Chippawa", paragraphs: ["At Chippawa on July 5, Scott's brigade advanced under fire and defeated a British force in a conventional engagement. The battle carried outsized institutional meaning for the U.S. Army because trained regulars—not a naval anomaly or defensive earthwork—had performed effectively in the open field.", "The victory did not open Upper Canada. Operational success still depended on supply, cooperation, and naval conditions on Lake Ontario." ] },
      { heading: "Lundy's Lane", paragraphs: ["Three weeks later near Niagara Falls, Brown's and Drummond's forces collided in a confused evening battle. Units fought at close range for artillery positions as darkness made command and identification difficult. Both sides suffered heavily; both later claimed success.", "American forces withdrew to Fort Erie. A battle can be tactically contested and strategically limiting at the same time. Lundy's Lane weakened the American army without giving Britain a clean destruction of it." ] },
      { heading: "Fort Erie and withdrawal", paragraphs: ["British forces besieged Fort Erie. Assault, sorties, rain, sickness, and an accidental explosion turned the position into another costly struggle. The British eventually lifted the siege; the Americans later evacuated and destroyed the fort.", "Black Upper Canadian militia service belonged to this theater, as did the labor of civilians and military communities that supplied both armies. The campaign ended with improved reputations and familiar geography: armies near the line from which they had started." ] }
    ], sourceRefs: ["lac", "parks-black-militia", "cwm"], relatedEvents: ["chippawa", "lundys-lane", "fort-erie"], communities: ["U.S. regulars", "British regulars", "Upper Canadian militia", "Black militia units"]
  },
  {
    id: "ch-13", slug: "plattsburgh", order: 13, eyebrow: "Chapter 13 · September 1814", title: "Plattsburgh: The Invasion That Turned Back", subtitle: "A lake battle makes a large army's position impossible", date: "6–11 September 1814", theaters: ["Lake Champlain", "Northern theater"],
    lede: "Plattsburgh is easy to underweight because it lacks a burned capital or future anthem. Strategically, it was one of the most consequential contests of the war.",
    sections: [
      { heading: "The corridor", paragraphs: ["A British army under Governor General George Prévost moved south along the Lake Champlain corridor. The route had carried armies before because the lake connected Canada to the Hudson system. But a large force on that route could not live indefinitely from wagons alone. Control of the water mattered.", "American land forces under Alexander Macomb prepared at Plattsburgh while Master Commandant Thomas Macdonough arranged his squadron in the bay. Macdonough anchored deliberately and rigged springs and kedge anchors so his vessels could rotate, bringing fresh broadsides to bear." ] },
      { heading: "The naval decision", paragraphs: ["On September 11, the British squadron attacked. The fight was brutal and close. Macdonough's preparations let USS Saratoga turn after one side's guns were disabled; the British flagship Confiance could not answer in the same way. The British squadron surrendered.", "Without command of the lake, Prévost judged his supply position untenable and withdrew, to the anger of officers who believed the land battle had scarcely begun. His decision became controversial in Britain, but the strategic logic was the same logic governing the Great Lakes throughout the war: an army could not ignore the fleet that sustained it." ] },
      { heading: "News for Ghent", paragraphs: ["The failure removed a powerful British bargaining asset. Negotiators at Ghent were not mechanically dictated by a single battle, but diplomacy occurred inside expectations about what could be held, demanded, or traded. Plattsburgh narrowed those expectations.", "At nearly the same moment, another British operation moved against Baltimore. The outcomes together weakened the prospect of imposing territorial concessions from a position of overwhelming success." ] }
    ], sourceRefs: ["nps-plattsburgh", "lac", "loc-ghent"], relatedEvents: ["lake-champlain", "prevost-withdrawal"], communities: ["American sailors", "British sailors", "New York militia", "British invasion force"]
  },
  {
    id: "ch-14", slug: "washington-burns", order: 14, eyebrow: "Chapter 14 · August 1814", title: "Washington Burns", subtitle: "A capital exposed, a defense broken, and a humiliation remembered", date: "19–25 August 1814", theaters: ["Chesapeake", "Washington", "Civilian"],
    lede: "The burning of Washington was not comic opera performed by incompetent politicians and a few British tourists. It was the result of strategic misjudgment, failed command, hard marching, naval pressure, and violence that opened paths to freedom for some while destroying security for others.",
    sections: [
      { heading: "Up the Patuxent", paragraphs: ["British forces landed at Benedict and advanced through southern Maryland. Rear Admiral George Cockburn's experience in the Chesapeake supplied intelligence and mobility; Major General Robert Ross commanded the army. Joshua Barney's Chesapeake Flotilla, trapped up the Patuxent, was destroyed to prevent capture. Its sailors and marines joined the defense on land.", "American leaders could not agree where the British intended to strike or who had authority to concentrate forces. Washington's symbolic importance did not create competent preparation." ] },
      { heading: "Bladensburg", paragraphs: ["At Bladensburg on August 24, American troops occupied poorly coordinated lines. British Congreve rockets added noise and fear, though later stories exaggerated their physical effect. Portions of the American force fought effectively—especially Barney's sailors and marines—but the position collapsed. President Madison and members of the cabinet had come dangerously close to the field; retreat became flight.", "The defeat opened Washington. British troops burned the Capitol, executive buildings, and military facilities. Americans had already set fire to the Navy Yard to deny stores and ships. A storm struck the city the next day. Myth later made the weather a providential avenger; it also spread fire and destruction." ] },
      { heading: "People inside the famous story", paragraphs: ["Dolley Madison helped ensure Gilbert Stuart's portrait of George Washington was removed from the President's House, but enslaved and free workers also carried property, messages, and responsibility through the crisis. The familiar version that isolates one heroic gesture compresses a larger household and civic emergency.", "British ships also represented possible liberation. Cochrane's proclamation offered reception to people willing to leave the United States, with choices of British military service or resettlement. Thousands of enslaved people sought British lines during the war. The policy was strategic warfare against American property and a real opening seized by people pursuing freedom. Both truths belong together." ] }
    ], sourceRefs: ["nhhc-flotilla", "nps-colonial", "nps-freedom-1", "loc-guide"], relatedEvents: ["bladensburg", "burning-washington", "navy-yard-burning"], communities: ["Chesapeake Flotilla", "Washington residents", "enslaved workers", "Colonial Marines"]
  },
  {
    id: "ch-15", slug: "baltimore-holds", order: 15, eyebrow: "Chapter 15 · September 1814", title: "Baltimore II: A City at War With an Empire", subtitle: "Earthworks, delay, bomb ships, and the night the city waited", date: "12–14 September 1814", theaters: ["Chesapeake", "Baltimore", "Naval"],
    lede: "In 1812, Baltimore's authorities could not keep a partisan mob from murdering a prisoner in the city jail. In 1814, the same city mobilized on a scale sufficient to stop an imperial expedition.",
    sections: [
      { heading: "The city becomes a fortress", paragraphs: ["Washington's destruction made Baltimore's danger immediate. Major General Samuel Smith oversaw an extensive defensive system: earthworks east of the city, harbor obstructions, Fort McHenry and supporting batteries, militia formations, federal troops, sailors, artillery, communications, stores, and thousands of laborers. Geography became an argument. A fleet could not simply sail past the harbor defenses; an army could not enter without confronting the line at Hampstead Hill.", "The work was civic as well as military. Free and enslaved Black laborers, white laborers, tradespeople, women, businesses, privateering networks, and officials all contributed under unequal conditions. “Baltimore united” is true only if it does not erase who had power, who was compelled, and how recent the city's political violence remained." ] },
      { heading: "North Point buys time", paragraphs: ["British troops landed at North Point on September 12. Ross rode forward and was mortally wounded in a skirmish; command passed to Colonel Arthur Brooke. Brigadier General John Stricker's militia line met the British advance. After hard fighting and pressure on his flank, Stricker conducted an orderly withdrawal.", "Calling North Point simply a British victory misses its defensive function. Stricker did not destroy the invaders, but his force delayed them, inflicted casualties, preserved much of the command, and returned to the prepared defenses. Brooke reached the edge of Baltimore facing earthworks occupied by a much larger force than the army routed at Bladensburg." ] },
      { heading: "The harbor holds", paragraphs: ["The naval attack began against Fort McHenry and the harbor defenses on September 13. British bomb vessels and a rocket ship fired from beyond the effective range of most American guns. Rain and low clouds obscured the scene. The famous bombardment was directed at the fortifications, not a continuous shelling of downtown Baltimore.", "During the night, British boats attempted to move toward the ferry branch and threaten the defenses from another direction. Fire from Forts Covington and Babcock helped repel them. The operation did not create the opening Brooke needed. With the harbor passage closed and the land defenses formidable, the British withdrew." ] },
      { heading: "The flag and the witness", paragraphs: ["Mary Pickersgill's household made two flags for Fort McHenry: a smaller storm flag and the immense garrison flag. Grace Wisher, a young African American indentured servant, worked in that household and is part of the object's history. The flag now at the Smithsonian is not merely a patriotic abstraction; it is cloth made through skilled labor performed inside Baltimore's racial and economic order.", "Francis Scott Key watched from a truce vessel after helping negotiate the release of Dr. William Beanes. At morning, the sight of the flag confirmed that the fort had not surrendered. His poem became a song, and much later the national anthem. The meaning accumulated afterward. The immediate fact was simpler: Baltimore remained in American hands." ] }
    ], sourceRefs: ["nps-baltimore", "nps-north-point", "nps-bombardment", "nps-grace", "smithsonian-flag", "loc-fort-print"], relatedEvents: ["north-point", "fort-mchenry", "british-withdraw-baltimore"], communities: ["Baltimore militia", "free Black Baltimoreans", "enslaved laborers", "women and girls", "British expedition"]
  },
  {
    id: "ch-16", slug: "peace-at-ghent", order: 16, eyebrow: "Chapter 16 · 1814–1815", title: "Peace at Ghent", subtitle: "The war aims shrink toward an agreement that restores the map", date: "August 1814–17 February 1815", theaters: ["Diplomacy", "Europe", "Atlantic world"],
    lede: "Peace did not arrive because everyone agreed what the war had meant. It arrived because neither government found the attainable rewards worth the continuing costs—and because battlefield news changed what each side believed it could demand.",
    sections: [
      { heading: "What Britain asked", paragraphs: ["British negotiators initially advanced demands shaped by apparent military advantage: boundary adjustments, limits on American power around the lakes, and an Indigenous buffer state in the Old Northwest. The proposed Native polity would have served British North American security and acknowledged allies whose military contribution had been essential.", "The United States rejected the buffer state, and Britain did not carry the demand to the final treaty. Indigenous representatives had no independent place at Ghent. As British leverage weakened and European priorities reasserted themselves, the negotiation moved toward restoring conquered territory rather than remaking the continent." ] },
      { heading: "What the treaty said", paragraphs: ["Signed on December 24, 1814, the Treaty of Ghent provided for restoration of territory, commissions to resolve boundary questions, and an end to hostilities after ratification. It called for ending warfare with Indigenous nations and restoring possessions and rights held in 1811, language the United States would not meaningfully enforce against its expansion.", "The treaty did not settle impressment or neutral maritime rights—the issues most prominent in Madison's public case for war. Napoleon's defeat had already reduced the immediate conditions that produced those disputes. Silence became politically easier than settlement." ] },
      { heading: "Peace at the speed of sail", paragraphs: ["A signature in Ghent did not instantaneously stop fighting in North America. News had to cross the Atlantic; the United States had to ratify; orders had to reach scattered forces. The Senate unanimously consented, Madison exchanged ratifications, and peace became effective in February 1815.", "Between signature and ratification came the war's most lopsided famous battle. New Orleans did not cause the treaty. It did shape the peace Americans believed they had won." ] }
    ], sourceRefs: ["loc-ghent", "cwm", "state-rush-bagot", "nps-indigenous"], relatedEvents: ["ghent-negotiations", "treaty-ghent", "us-ratification"], communities: ["American diplomats", "British diplomats", "Indigenous nations excluded from the table", "Atlantic messengers"]
  },
  {
    id: "coda", slug: "new-orleans", order: 17, eyebrow: "Coda · 1814–1815", title: "New Orleans: The Battle After Peace Was Signed", subtitle: "A diverse city, a slow communications world, and a victory that rewrote memory", date: "December 1814–January 1815", theaters: ["Gulf", "Louisiana", "Naval"],
    lede: "The treaty existed in Europe. Peace did not yet exist in Louisiana. Commanders acted in the communications world they inhabited, not the one later readers wish they had.",
    sections: [
      { heading: "Before January 8", paragraphs: ["British Gulf operations included attacks on Fort Bowyer and cooperation with forces at Pensacola. Jackson seized Pensacola in November, then hurried to New Orleans. The British reached Lake Borgne, defeated an American gunboat flotilla, landed below the city, and surprised defenders by how close they had come.", "On December 23, Jackson attacked the British camp. The action was confused and indecisive, but it disrupted British momentum and bought time. Americans strengthened a line along the Rodriguez Canal at Chalmette while British forces brought up men and artillery." ] },
      { heading: "Coalitions on both sides", paragraphs: ["Jackson's force joined U.S. regulars, Louisiana militia, free men of color organized in battalions, Tennessee and Kentucky militia, Choctaw fighters, Baratarians, sailors, marines, Creoles, and Black participants whose legal status and roles require precise case-by-case evidence. Jordan Noble, a free Black drummer, became one named participant in a much larger military community.", "The British army was no less imperial: regular regiments, Royal Marines, sailors, and Black soldiers of the West India Regiments. Describing the action as Americans versus British is accurate at the level of states and incomplete at the level of people." ] },
      { heading: "January 8", paragraphs: ["The British assault on January 8 failed catastrophically. Terrain, canal, earthworks, American artillery, disrupted fascine and ladder plans, command breakdown, and exposed formations combined to turn advance into slaughter. Major General Edward Pakenham was killed. American casualties were light by comparison.", "The victory did not save a treaty signed two weeks earlier. Nor was it pointless. People died; the Gulf campaign continued briefly; the outcome transformed Jackson's political future and American memory of the war. It made an ambiguous settlement feel like vindication." ] },
      { heading: "The Manilamen question", paragraphs: ["Filipino people were present in early Louisiana, and Saint Malo later became a documented Filipino fishing community. Traditions and secondary retellings place “Manilamen” among Lafitte's Baratarians or the defenders of New Orleans. Surviving contemporary evidence has not established a large, precisely numbered Filipino contingent at Chalmette.", "The responsible course is neither inflation nor erasure. The community, maritime networks, and tradition belong in the story; the battlefield claim must carry its evidence status: plausible in individual cases, preserved in later community memory, but unresolved in number and organization." ], evidence: { familiar: "Filipino Manilamen fought as a distinct contingent under Lafitte at New Orleans.", documented: "Filipino presence in Louisiana and the later Saint Malo community are documented; the Baratarian world was multinational.", uncertain: "The identities and number of Filipino combatants present on January 8 are not firmly established in surviving contemporary records." } }
    ], sourceRefs: ["nps-new-orleans-black", "nps-choctaw", "lafolklife", "nps-creek"], relatedEvents: ["lake-borgne", "night-battle-december-23", "new-orleans"], communities: ["free Black battalions", "Louisiana Creoles", "Choctaw fighters", "Baratarians", "West India Regiments", "Filipino Louisiana"]
  },
  {
    id: "epilogue", slug: "what-changed", order: 18, eyebrow: "Epilogue · After 1815", title: "What Did the War Change?", subtitle: "Outcomes, consequences, and memories are not the same thing", date: "1815 and after", theaters: ["United States", "British North America", "Indigenous homelands", "Atlantic world"],
    lede: "The treaty restored the map. The war transformed power, memory, and possibility unevenly. Asking who won requires deciding whose aims, whose losses, and what time horizon count.",
    sections: [
      { heading: "The states", paragraphs: ["The United States failed to conquer Canada and won no maritime concession in the treaty. It did survive war with the world's leading naval power, end with dramatic defensive victories, and experience a surge of nationalism. The Federalist Party's opposition—especially the badly timed Hartford Convention—became politically toxic. Jackson emerged as a national hero. Manufacturing expanded behind disrupted trade.", "Britain preserved British North America, ended an unwanted secondary war, and returned attention to Europe and empire. It did not crush the American republic or secure a Native buffer state. In Britain the war became comparatively forgettable because it stood beside the defeat of Napoleon." ] },
      { heading: "British North America and later Canada", paragraphs: ["Upper and Lower Canada remained within the British Empire. Local militia service and resistance to invasion supplied later Canadian memory with powerful material. But modern Canada did not fight as a sovereign nation in 1812, and later national unity should not be projected backward over French-speaking, English-speaking, Black, Indigenous, imperial, and local experiences.", "The Rush–Bagot arrangement limited naval forces on the Great Lakes, while the Convention of 1818 addressed boundaries and shared occupation in the northwest. The border gradually became less militarized not because the war settled every dispute, but because later governments chose management over renewal." ] },
      { heading: "The unequal peace", paragraphs: ["For Tecumseh's coalition and many Native nations, Britain’s abandonment of the buffer-state demand was decisive. American expansion accelerated; land cessions, forced movement, and military pressure continued. Article IX of the treaty could not restore the political leverage lost with lives, territory, and alliance.", "Thousands of Black refugees left slavery through British lines. Some settled in Nova Scotia; Colonial Marines and families formed “Merikin” communities in Trinidad; others faced hardship, discrimination, or renewed insecurity. Black Americans who served the United States returned to a republic that celebrated their military usefulness without dismantling racial exclusion or slavery." ] },
      { heading: "Who won?", paragraphs: ["If the question concerns the treaty line, the answer is restoration. If it concerns the survival of British North America, Britain and its colonies achieved a central aim. If it concerns American national confidence, the United States built a durable victory narrative. If it concerns Indigenous autonomy in the Old Northwest, the result was catastrophic.", "Those answers do not cancel one another because the participants did not enter the war seeking the same thing. “Nobody won” is too neat; “everyone won” is false. The war ended in a negotiated status quo between states and a radical deterioration of power for many people the states did not treat as equal parties." ] }
    ], sourceRefs: ["nps-legacies", "state-rush-bagot", "nps-freedom-1", "nps-indigenous", "cwm"], relatedEvents: ["rush-bagot", "convention-1818", "black-refugee-resettlement"], communities: ["Black Refugees", "Merikin communities", "Indigenous nations", "American veterans", "British North American residents"]
  },
];

export type EventRecord = {
  id: string; date: string; year: number; title: string; place: string; theater: string; type: string; summary: string; chapter: string; x: number; y: number; sourceRefs: string[];
};

export const events: EventRecord[] = [
  { id:"chesapeake-leopard", date:"22 June 1807", year:1807, title:"Chesapeake–Leopard affair", place:"off Norfolk, Virginia", theater:"Atlantic", type:"naval", summary:"HMS Leopard fires on USS Chesapeake after an refused search, intensifying the dispute over impressment and sovereignty.", chapter:"world-already-at-war", x:70, y:51, sourceRefs:["nara-impressment"] },
  { id:"tippecanoe", date:"7 November 1811", year:1811, title:"Battle of Tippecanoe", place:"Prophetstown, Indiana Territory", theater:"Old Northwest", type:"Indigenous", summary:"Harrison's force fights Tenskwatawa's followers; Americans increasingly connect Indigenous resistance to British power.", chapter:"world-already-at-war", x:45, y:41, sourceRefs:["nps-indigenous"] },
  { id:"war-declaration", date:"18 June 1812", year:1812, title:"United States declares war", place:"Washington, D.C.", theater:"Politics", type:"political", summary:"Madison signs the declaration after divided votes in the House and Senate.", chapter:"why-war", x:69, y:47, sourceRefs:["house-declaration"] },
  { id:"baltimore-riot-june", date:"22 June 1812", year:1812, title:"Federal Republican press destroyed", place:"Baltimore, Maryland", theater:"Chesapeake", type:"civilian", summary:"A pro-war crowd destroys the office and press of an antiwar newspaper.", chapter:"baltimore-at-war-with-itself", x:70, y:45, sourceRefs:["nps-riots"] },
  { id:"baltimore-jail-massacre", date:"28 July 1812", year:1812, title:"Baltimore jail massacre", place:"Baltimore, Maryland", theater:"Chesapeake", type:"civilian", summary:"A mob breaks into the jail, murders James M. Lingan, and brutally attacks Hanson, Lee, and other Federalists.", chapter:"baltimore-at-war-with-itself", x:70, y:45, sourceRefs:["nps-riots"] },
  { id:"detroit-surrender", date:"16 August 1812", year:1812, title:"Surrender of Detroit", place:"Detroit, Michigan Territory", theater:"Great Lakes", type:"battle", summary:"Hull surrenders to Brock's smaller British, Canadian, and Indigenous force without an assault.", chapter:"easy-conquest-that-wasnt", x:47, y:32, sourceRefs:["cwm","lac"] },
  { id:"constitution-guerriere", date:"19 August 1812", year:1812, title:"Constitution defeats Guerriere", place:"North Atlantic", theater:"Atlantic", type:"naval", summary:"The first spectacular American frigate victory creates the legend of “Old Ironsides.”", chapter:"old-ironsides", x:83, y:38, sourceRefs:["nhhc"] },
  { id:"queenston-heights", date:"13 October 1812", year:1812, title:"Battle of Queenston Heights", place:"Niagara River, Upper Canada", theater:"Great Lakes", type:"battle", summary:"British, Canadian, and Indigenous forces defeat an American crossing; Isaac Brock is killed.", chapter:"easy-conquest-that-wasnt", x:55, y:30, sourceRefs:["cwm","lac"] },
  { id:"united-states-macedonian", date:"25 October 1812", year:1812, title:"United States captures Macedonian", place:"mid-Atlantic", theater:"Atlantic", type:"naval", summary:"Stephen Decatur's frigate captures a valuable British warship and brings the prize into port.", chapter:"old-ironsides", x:84, y:46, sourceRefs:["nhhc"] },
  { id:"york", date:"27 April 1813", year:1813, title:"Capture and burning at York", place:"York, Upper Canada", theater:"Great Lakes", type:"occupation", summary:"American forces capture the colonial capital; looting and burning feed a later retaliation narrative.", chapter:"war-reaches-homes", x:54, y:29, sourceRefs:["cwm"] },
  { id:"sackets-harbor", date:"29 May 1813", year:1813, title:"Second Battle of Sackets Harbor", place:"Sackets Harbor, New York", theater:"Great Lakes", type:"battle", summary:"A British attack fails to destroy the principal American Lake Ontario naval base.", chapter:"continental-naval-arms-race", x:61, y:28, sourceRefs:["lac"] },
  { id:"chesapeake-shannon", date:"1 June 1813", year:1813, title:"Shannon captures Chesapeake", place:"off Boston, Massachusetts", theater:"Atlantic", type:"naval", summary:"A British frigate wins a close action; James Lawrence's last command becomes an American motto.", chapter:"old-ironsides", x:78, y:30, sourceRefs:["nhhc"] },
  { id:"havre-de-grace", date:"3 May 1813", year:1813, title:"Raid on Havre de Grace", place:"Havre de Grace, Maryland", theater:"Chesapeake", type:"raid", summary:"British forces burn and plunder much of the town during the widening Chesapeake campaign.", chapter:"war-reaches-homes", x:70, y:42, sourceRefs:["nps-living"] },
  { id:"fort-mims", date:"30 August 1813", year:1813, title:"Fort Mims attack", place:"Mississippi Territory", theater:"Gulf", type:"battle", summary:"Red Stick warriors overrun Fort Mims; mass death drives American mobilization in the Creek War.", chapter:"southern-borderlands", x:52, y:72, sourceRefs:["nps-creek"] },
  { id:"lake-erie", date:"10 September 1813", year:1813, title:"Battle of Lake Erie", place:"Lake Erie", theater:"Great Lakes", type:"naval", summary:"Perry's squadron captures its British opponent, forcing the evacuation of Detroit.", chapter:"war-for-the-interior", x:48, y:34, sourceRefs:["nps-lake-erie"] },
  { id:"battle-thames", date:"5 October 1813", year:1813, title:"Battle of the Thames", place:"Upper Canada", theater:"Old Northwest", type:"battle", summary:"Harrison defeats a retreating British and Indigenous force; Tecumseh is killed and his coalition gravely weakened.", chapter:"war-for-the-interior", x:47, y:31, sourceRefs:["nps-indigenous"] },
  { id:"burning-newark", date:"10 December 1813", year:1813, title:"Burning of Newark", place:"Newark, Upper Canada", theater:"Niagara", type:"civilian", summary:"Retreating American forces burn the town, leaving civilians exposed and intensifying retaliation.", chapter:"war-reaches-homes", x:55, y:31, sourceRefs:["cwm"] },
  { id:"essex-pacific", date:"1813", year:1813, title:"Essex enters the Pacific", place:"Pacific Ocean", theater:"Pacific", type:"naval", summary:"David Porter attacks British whaling and assembles prizes into an improvised squadron.", chapter:"war-around-cape-horn", x:8, y:70, sourceRefs:["nhhc-pacific"] },
  { id:"nuku-hiva", date:"October–December 1813", year:1813, title:"Essex at Nuku Hiva", place:"Marquesas Islands", theater:"Pacific", type:"occupation", summary:"Porter refits, intervenes in local conflicts, and makes an ineffective American territorial claim.", chapter:"war-around-cape-horn", x:5, y:57, sourceRefs:["nhhc-pacific"] },
  { id:"horseshoe-bend", date:"27 March 1814", year:1814, title:"Battle of Horseshoe Bend", place:"Muscogee homelands", theater:"Gulf", type:"battle", summary:"Jackson's American, Cherokee, and allied Muscogee force breaks Red Stick resistance.", chapter:"southern-borderlands", x:55, y:68, sourceRefs:["nps-creek"] },
  { id:"valparaiso", date:"28 March 1814", year:1814, title:"Defeat of USS Essex", place:"Valparaíso, Chile", theater:"Pacific", type:"naval", summary:"HMS Phoebe and Cherub defeat Porter's damaged frigate near the neutral port.", chapter:"war-around-cape-horn", x:13, y:81, sourceRefs:["nhhc-pacific"] },
  { id:"napoleon-abdication", date:"6 April 1814", year:1814, title:"Napoleon's first abdication", place:"Fontainebleau, France", theater:"Europe", type:"political", summary:"The end of the European campaign releases British attention and veteran troops for North America.", chapter:"everything-changes", x:94, y:28, sourceRefs:["cwm"] },
  { id:"chippawa", date:"5 July 1814", year:1814, title:"Battle of Chippawa", place:"Upper Canada", theater:"Niagara", type:"battle", summary:"Scott's trained American regulars defeat a British force in open battle.", chapter:"niagara-again", x:55, y:31, sourceRefs:["lac"] },
  { id:"lundys-lane", date:"25 July 1814", year:1814, title:"Battle of Lundy's Lane", place:"Upper Canada", theater:"Niagara", type:"battle", summary:"A close, confused night battle causes severe casualties and no clean strategic result.", chapter:"niagara-again", x:55, y:31, sourceRefs:["lac"] },
  { id:"treaty-fort-jackson", date:"9 August 1814", year:1814, title:"Treaty of Fort Jackson", place:"Alabama Territory", theater:"Gulf", type:"diplomatic", summary:"Jackson imposes a vast Muscogee land cession, including land of U.S. allies.", chapter:"southern-borderlands", x:54, y:70, sourceRefs:["nps-creek"] },
  { id:"bladensburg", date:"24 August 1814", year:1814, title:"Battle of Bladensburg", place:"Maryland", theater:"Chesapeake", type:"battle", summary:"British forces rout a poorly coordinated American defense and open the road to Washington.", chapter:"washington-burns", x:69, y:48, sourceRefs:["nhhc-flotilla"] },
  { id:"burning-washington", date:"24–25 August 1814", year:1814, title:"Burning of Washington", place:"Washington, D.C.", theater:"Chesapeake", type:"occupation", summary:"British troops burn public buildings; Americans destroy the Navy Yard to deny it to the enemy.", chapter:"washington-burns", x:69, y:49, sourceRefs:["loc-guide"] },
  { id:"lake-champlain", date:"11 September 1814", year:1814, title:"Battle of Lake Champlain", place:"Plattsburgh, New York", theater:"Lake Champlain", type:"naval", summary:"Macdonough defeats the British squadron, making Prévost's invasion unsustainable.", chapter:"plattsburgh", x:67, y:25, sourceRefs:["nps-plattsburgh"] },
  { id:"north-point", date:"12 September 1814", year:1814, title:"Battle of North Point", place:"Baltimore County, Maryland", theater:"Chesapeake", type:"battle", summary:"Stricker's militia delays the British advance; Ross is mortally wounded.", chapter:"baltimore-holds", x:71, y:45, sourceRefs:["nps-north-point"] },
  { id:"fort-mchenry", date:"13–14 September 1814", year:1814, title:"Bombardment of Fort McHenry", place:"Baltimore, Maryland", theater:"Chesapeake", type:"naval", summary:"The fort and harbor defenses withstand British bombs, rockets, and a nighttime boat movement.", chapter:"baltimore-holds", x:70, y:45, sourceRefs:["nps-bombardment"] },
  { id:"pensacola", date:"7 November 1814", year:1814, title:"Jackson takes Pensacola", place:"Spanish West Florida", theater:"Gulf", type:"occupation", summary:"American forces expel a British presence from the Spanish port before moving to defend New Orleans.", chapter:"new-orleans", x:50, y:75, sourceRefs:["nps-prince-witten"] },
  { id:"lake-borgne", date:"14 December 1814", year:1814, title:"Battle of Lake Borgne", place:"Louisiana", theater:"Gulf", type:"naval", summary:"British boats defeat an American gunboat flotilla and clear the approach to New Orleans.", chapter:"new-orleans", x:45, y:79, sourceRefs:["nps-new-orleans-black"] },
  { id:"treaty-ghent", date:"24 December 1814", year:1814, title:"Treaty of Ghent signed", place:"Ghent", theater:"Diplomacy", type:"diplomatic", summary:"British and American commissioners sign a treaty restoring conquered territory but leaving maritime disputes unsettled.", chapter:"peace-at-ghent", x:96, y:24, sourceRefs:["loc-ghent"] },
  { id:"night-battle-december-23", date:"23 December 1814", year:1814, title:"Night battle below New Orleans", place:"Louisiana", theater:"Gulf", type:"battle", summary:"Jackson attacks the British camp, disrupting its advance and buying time for stronger defenses.", chapter:"new-orleans", x:43, y:79, sourceRefs:["nps-new-orleans-black"] },
  { id:"new-orleans", date:"8 January 1815", year:1815, title:"Battle of New Orleans", place:"Chalmette, Louisiana", theater:"Gulf", type:"battle", summary:"A diverse American force defeats the main British assault with devastating losses.", chapter:"new-orleans", x:43, y:79, sourceRefs:["nps-new-orleans-black","nps-choctaw"] },
  { id:"us-ratification", date:"17 February 1815", year:1815, title:"Peace becomes effective", place:"Washington, D.C.", theater:"Diplomacy", type:"diplomatic", summary:"Ratifications are exchanged and the United States proclaims peace.", chapter:"peace-at-ghent", x:69, y:48, sourceRefs:["loc-ghent"] },
  { id:"rush-bagot", date:"1817", year:1817, title:"Rush–Bagot arrangement", place:"Great Lakes", theater:"Diplomacy", type:"diplomatic", summary:"The United States and Britain limit naval armaments on the Great Lakes.", chapter:"what-changed", x:54, y:30, sourceRefs:["state-rush-bagot"] },
];

export const sourceById = Object.fromEntries(sources.map((source) => [source.id, source]));
export const chapterBySlug = Object.fromEntries(chapters.map((chapter) => [chapter.slug, chapter]));
export const chapterById = Object.fromEntries(chapters.map((chapter) => [chapter.id, chapter]));

export function chapterHref(chapterRef: string) {
  const chapter = chapterById[chapterRef] ?? chapterBySlug[chapterRef];
  return chapter ? `/story/${chapter.slug}` : "/story";
}
