export type IdentityConfidence = "Confirmed identity" | "Strong match" | "Index-level match" | "Unresolved match";

export type HumanRecord = {
  slug: string;
  name: string;
  group: string;
  role: string;
  dates?: string;
  places: string[];
  events: string[];
  unit?: string;
  allegiances: string[];
  identityConfidence: IdentityConfidence;
  confidenceNote: string;
  archiveReason: string;
  sourceRefs: string[];
  chapter: string;
  relationships: { target: string; label: string }[];
  movements: { date: string; place: string; note: string }[];
  detail: "dossier" | "index";
};

type GroupSeed = Omit<HumanRecord, "slug" | "name" | "relationships" | "movements" | "detail"> & { names: string };
const slugify = (name: string) => name.toLowerCase().normalize("NFKD").replace(/[’'“”".]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

const seeds: GroupSeed[] = [
  {
    group:"Political and diplomatic records", role:"Named political or diplomatic actor", places:["Washington", "Ghent", "London"], events:["War debate", "wartime administration", "peace negotiations"], unit:"Civil government and diplomatic service", allegiances:["United States or Great Britain—verify at record level"], identityConfidence:"Index-level match", confidenceNote:"Name and wartime context are supported by government, diplomatic, or congressional records; full identity reconciliation remains a research task.", archiveReason:"This person enters the archive through officeholding, correspondence, voting, appointment, negotiation, or publication—forms of visibility produced by political power.", sourceRefs:["house-declaration","loc-ghent","loc-manuscripts"], chapter:"why-war",
    names:`James Madison|Dolley Madison|James Monroe|Elizabeth Kortright Monroe|Albert Gallatin|John Quincy Adams|Henry Clay|Jonathan Russell|James A. Bayard|William H. Crawford|Robert Smith|William Eustis|John Armstrong Jr.|George W. Campbell|Alexander J. Dallas|Richard Rush|John C. Calhoun|Langdon Cheves|Felix Grundy|George M. Troup|Josiah Quincy III|John Randolph of Roanoke|Timothy Pickering|Harrison Gray Otis|Daniel Webster|Rufus King|DeWitt Clinton|Elbridge Gerry|William Pinkney|Augustus John Foster|David Erskine|Anthony St. John Baker|Charles Bagot|Robert Stewart, Viscount Castlereagh|Robert Jenkinson, Lord Liverpool|Henry Bathurst|Henry Goulburn|James Gambier|William Adams|John Mason|William Jones|Benjamin Crowninshield|John Graham|Christopher Gore|William Lowndes|Nathaniel Macon|Nathaniel Pope|John Smilie|Roger Nelson|Samuel Taggart|Harmanus Bleecker|James Lloyd|Abijah Bigelow|Laban Wheaton|James Barbour|Charles Tait|William Branch Giles|Obadiah German|Michael Leib|William Reed|Nicholas Gilman|John Gaillard|William Wyatt Bibb|Outerbridge Horsey|Joseph Anderson`
  },
  {
    group:"United States Army and militia", role:"Named officer, soldier, militiaman, or military administrator", places:["United States", "Great Lakes", "Chesapeake", "Gulf Coast"], events:["Land campaigns", "garrison duty", "mobilization"], unit:"U.S. Army or state militia—see service record", allegiances:["United States"], identityConfidence:"Index-level match", confidenceNote:"The individual is named in military histories, service files, unit records, or campaign documentation; namesakes and spelling variants require record-level confirmation.", archiveReason:"Military systems created rolls, returns, courts-martial, correspondence, pension claims, casualty lists, and orders. Those systems preserved some soldiers while reducing others to a line on a form.", sourceRefs:["nara-war","nps-war","loc-guide"], chapter:"easy-conquest-that-wasnt",
    names:`William Hull|Henry Dearborn|Wade Hampton I|James Wilkinson|William Henry Harrison|Winfield Scott|Jacob Brown|Edmund P. Gaines|Eleazer Wheelock Ripley|James Miller|George Croghan|Alexander Macomb|George Izard|Duncan McArthur|Lewis Cass|Alexander Smyth|Stephen Van Rensselaer|Solomon Van Rensselaer|William Wadsworth|Zebulon Pike|Thomas Jesup|Nathan Towson|Jacob Hindman|George Armistead|John Stricker|Samuel Smith|Joshua Barney|William H. Winder|Tobias Stansbury|Joseph Sterett|Levin Winder|John Coffee|William Carroll|John Adair|Thomas Hinds|Samuel Hopkins|Joseph Graham|John Williams|Richard Mentor Johnson|Isaac Shelby|Green Clay|Leonard Covington|James Winchester|John Parker Boyd|Moses Porter|George McClure|Peter Buell Porter|Hugh Brady|Enos Stone|Joseph Willcocks|Joseph G. Swift|Joseph Bloomfield|Morgan Lewis|Daniel Bissell|Alexander Cummings|Thomas Flournoy|John Chandler|Robert Swartwout|Joseph Anderson|James Simons|Charles Boerstler|Joseph Eldridge|John Chrystie|John Fenwick|Abraham Eustis|Daniel Appling|Thomas Sidney Jesup|Thomas Benton|Benjamin Forsyth|Daniel Davis|Nathaniel Rochester|George McFeely|James House|John Bankhead|George Mitchell|David B. Mitchell|John Floyd|Samuel Blackburn|William McIntosh|Andrew Jackson|John Thomas|John Pegram|John Gibson|William Butler|Samuel Dale|Ferdinand Claiborne|Thomas Flournoy|John Cocke|John Alexander|William Russell|Robert Butler|Daniel Carmick|William McRea|Henry D. Peire|George T. Ross|Jacques Villeré|Pierre de La Ronde|Jean Baptiste Plauché|Pierre Lacoste|Louis D’Aquin|Thomas Beale`
  },
  {
    group:"Naval, privateering, and maritime labor", role:"Named naval officer, privateer, shipbuilder, sailor, or maritime agent", places:["Atlantic", "Great Lakes", "Chesapeake", "Gulf of Mexico"], events:["Naval operations", "privateering", "ship construction"], unit:"Naval vessel, yard, or private armed ship—see source route", allegiances:["Maritime service—verify at record level"], identityConfidence:"Index-level match", confidenceNote:"Name and maritime context are supported; shipboard names, prize records, and repeated family names may require additional matching.", archiveReason:"Prize courts, ship musters, logbooks, payrolls, contracts, protection certificates, and casualty reports made maritime work unusually document-rich—while still obscuring coerced labor and men recorded under unstable identities.", sourceRefs:["nhhc","nps-privateers","nara-impressment"], chapter:"old-ironsides",
    names:`John Rodgers|William Bainbridge|Isaac Hull|Stephen Decatur|Charles Stewart|Jacob Jones|David Porter|Isaac Chauncey|Jesse Duncan Elliott|William Burrows|William Henry Allen|James Biddle|Lewis Warrington|Johnston Blakeley|John Downes|Thomas Macdonough|Oliver Hazard Perry|James Lawrence|Charles Morris|Arthur Sinclair|Melancthon Taylor Woolsey|Thomas ap Catesby Jones|Daniel Todd Patterson|George Campbell Read|Joseph Tarbell|John Percival|Joseph Bainbridge|David Conner|Alexander Scammel Wadsworth|Edward Trenchard|Robert Henley|Daniel Turner|Jesse Wilkinson|Samuel Angus|Thomas Brown|George Parker|John Orde Creighton|John Renshaw|William Crane|John Shaw|John Cassin|Jesse D. Elliott|Thomas Holdup Stevens|John Pettigrew|Thomas Boyle|William Josephus Stafford|John Ordronaux|Pearl Durkee|William Wade|George R. Roberts|Richard Moon|Thomas Kemp|George Stiles|Jeremiah Mitchell|Luke Tiernan|Vincent Nolte|Jean Lafitte|Pierre Lafitte|Renato Beluche|Dominique You|Andrew Holmes|John Murphy|Benjamin Crowninshield|Samuel Hambleton|George Mitchell|Daniel Dobbins|Noah Brown|Henry Eckford|Adam Brown|Charles Browne|Abraham Bloodgood|Christian Bergh|John Floyd|Josiah Fox|William Doughty|Samuel Humphreys|William Rush|Francis Grice|Thomas Tennant|William Flanagan|John Clough|Joseph Snow|William Lord|Charles Ridgely|John S. Skinner|George Stiles Jr.|Peter Chazotte|William Westcott|Thomas Sangster|John H. Sherburne`
  },
  {
    group:"British, Canadian, and imperial service", role:"Named British, Canadian, or imperial military and civil participant", places:["British North America", "Atlantic", "Chesapeake", "Gulf Coast"], events:["Defense of Canada", "British offensives", "imperial administration"], unit:"British Army, Royal Navy, militia, or civil service", allegiances:["British Empire"], identityConfidence:"Index-level match", confidenceNote:"Name and service context are supported in imperial or Canadian records; rank dates and similarly named officers require record-level checking.", archiveReason:"Imperial command, naval administration, militia organization, correspondence, and honors generated records. Enlisted people, local laborers, and Indigenous allies often appear less fully than senior officers.", sourceRefs:["lac-british-records","uk-discovery","cwm"], chapter:"easy-conquest-that-wasnt",
    names:`George Prévost|Isaac Brock|Roger Hale Sheaffe|Gordon Drummond|Henry Procter|Phineas Riall|Robert Ross|Edward Pakenham|John Keane|John Lambert|Alexander Cochrane|George Cockburn|John Borlase Warren|James Lucas Yeo|Robert Heriot Barclay|George Downie|Philip Broke|James Richard Dacres|John Carden|James Hillyar|William Thornton|Thomas Mullins|Charles Napier|Frederick Heriot|Charles de Salaberry|John Vincent|John Harvey|James FitzGibbon|Thomas Pearson|John Murray|Richard Bullock|Thomas Evans|Thomas Carleton|John Sherbrooke|John Coape Sherbrooke|Manley Power|Edward Baynes|Noah Freer|William Claus|Matthew Elliott|Robert Nichol|Thomas Ridout|William Merritt|John Strachan|John Beverley Robinson|Thomas Talbot|William Robinson|George Macdonell|Charles Michel de Salaberry|John By|Daniel McDouall|Robert McDouall|George Glasgow|Thomas Scott|William Drummond|John Le Couteur|Charles Plenderleath|William Worsley|George McGregor|William Caldwell|William Hamilton Merritt|George Theodore Barlow|Thomas Bligh|Joseph Wanton Morrison|Charles Brisbane|Thomas Masterman Hardy|Edward Owen|Thomas Ussher|Henry Hope|Edward Codrington|Thomas Fremantle|Pulteney Malcolm|George Burdett|William Fahie|Edward Troubridge|Robert Barrie|Thomas Cochrane|Peter Parker|George Lewis|George Urmston|James Scott|Henry Noble Shipton|William Brooke|Arthur Brooke|Harry Smith|James Macdonell|Richard Pierpoint|Runchey|Robert Grant|John Norton`
  },
  {
    group:"Indigenous nations and coalitions", role:"Named Indigenous political, military, or diplomatic participant", places:["Great Lakes", "Old Northwest", "Southeast", "St. Lawrence borderlands"], events:["Indigenous diplomacy", "coalition warfare", "land defense"], unit:"Nation, town, kin network, or coalition—do not reduce to imperial auxiliary status", allegiances:["Indigenous nation or coalition", "Imperial alliance may be strategic and contingent"], identityConfidence:"Strong match", confidenceNote:"The name and broad wartime role are supported, but English-language spellings, translated names, kin relations, and imposed national categories can distort identity.", archiveReason:"Many named Indigenous people enter surviving archives when colonial officials negotiated with, fought, paid, translated, surveilled, or dispossessed them. The archive often describes alliance while failing to preserve Indigenous political reasoning in equal depth.", sourceRefs:["nps-indigenous","lac","cwm"], chapter:"war-for-the-interior",
    names:`Tecumseh|Tenskwatawa|Roundhead|Walk-in-the-Water|Main Poc|Black Hawk|Shabbona|Waubonsie|Winamac|Metea|Black Partridge|Red Jacket|Farmer’s Brother|Young King|Captain Pollard|John Norton|John Brant|Black Snake|Captain Cold|Little Billy|Menawa|William Weatherford|Peter McQueen|Josiah Francis|Paddy Walsh|William McIntosh|Major Ridge|Pathkiller|John Ross|Pushmataha|Mushulatubbee|Hopothle Mico|Little Prince|Big Warrior|Junaluska|John Lowrey|Tustunnuggee Thlucco|Hillabee Chief|Peter Cornells|High Head Jim|Monahoe|Opothleyahola|William Perryman|Chief Chinnabee|Captain Isaacs|Captain Steele|Captain Monture|John Smoke Johnson|John Brant Dekarihokenh|Teyoninhokarawen|Captain Norton|Tehowagherengaraghkwin|John Deserontyon|Black Bird|Mad Sturgeon|White Loon|Split Log|Captain Johnny|Little Otter|Nan-non-see|Wabasha II|Little Crow|Tahkanne|Wapasha|The Crane|The Owl|Checote|Tuskegee Tustunnuggee|Jim Fife`
  },
  {
    group:"Women, households, print, and civilian witness", role:"Named civilian, writer, worker, witness, or household participant", places:["Baltimore", "Washington", "Chesapeake", "Upper Canada"], events:["Household labor", "occupation", "public memory", "print culture"], unit:"Household, business, print shop, or community network", allegiances:["Civilian position—may not map cleanly to military allegiance"], identityConfidence:"Strong match", confidenceNote:"The named person and context are supported; household records and later recollections vary in detail and often assign credit unevenly.", archiveReason:"This person appears because correspondence, claims, household accounts, newspapers, memoirs, property, wage labor, or later commemoration made the life recoverable. Many other civilians remain unnamed because the same record-making systems did not value their testimony.", sourceRefs:["nps-women-chesapeake","loc-newspapers","nps-living"], chapter:"war-reaches-homes",
    names:`Mary Pickersgill|Grace Wisher|Rebecca Young|Caroline Pickersgill|Margaret Young|Eliza Young|Mary Young|Louisa Armistead|Margaret Bayard Smith|Ann Matilda Hanson|Rachel Jackson|Laura Secord|Betsy Doyle|Jane Barnes|Mary Henry|Rosalie Stier Calvert|Kitty Knight|Anna Tuthill Symmes Harrison|Margaret Mackall Smith Taylor|Rebecca Wilkinson|Elizabeth Patterson Bonaparte|Sarah Ridout|Mary Beanes|Anna Maria Brodeau Thornton|Henrietta Liston|Lydia Huntley Sigourney|Sarah Josepha Hale|Mary Ann Bent|Mary Tayloe Lloyd Key|Elizabeth Phoebe Key|Mary Ann Armistead|Georgiana Armistead|Judith Armistead|Anna Maria Fitzhugh|Elizabeth Monroe Hay|Eliza Kortright Monroe Hay|Catherine Armistead|Sally McKean|Susan Decatur|Maria Mayo Scott|Margaret Smith Brown|Elizabeth Brown|Sarah Brown|Jane Irwin Harrison|Mary Ann Custis Lee|Eleanor Parke Custis Lewis|Sukey Young|Harriet Douglas|Mary Douglass|Margaret Stuart|Susan Wheeler Decatur|Sophia Dallas Bache|Anne Willing Bingham|Margaret Carr`
  },
  {
    group:"Black service, freedom seeking, and the Gulf coalition", role:"Named Black participant, freedom seeker, militiaman, mariner, or borderlands actor", places:["Chesapeake", "Upper Canada", "Gulf Coast", "Florida", "Trinidad", "Nova Scotia"], events:["Black military service", "freedom seeking", "New Orleans", "resettlement"], unit:"Free Black militia, Colonial Marines, maritime crew, or community network", allegiances:["Allegiance and freedom strategy require individual context"], identityConfidence:"Strong match", confidenceNote:"The named person and broad context are supported; racial labels, aliases, coerced status, and later tradition require careful identity work.", archiveReason:"These lives often survive because military, slaveholding, prize, pension, claims, court, or resettlement systems needed to classify, pay, punish, transport, or control them. The record may document a transaction more fully than a person.", sourceRefs:["nps-new-orleans-black","nps-colonial","nps-freedom-1"], chapter:"new-orleans",
    names:`Richard Pierpoint|George R. Roberts|Jordan Noble|Jean Baptiste Savary|Joseph Savary|Louis D’Aquin|Pierre Lacoste|Dominique You|Charles Ball|Prince Witten|George Lewis|William Williams|Caesar|Harry Jones|Jack Punch|Isaac Hammond|William Hammond|Jacob Cuffee|London Feribee|Daniel Coker|William Costin|Michael Shiner|Paul Jennings`
  },
  {
    group:"Baltimore and Maryland records", role:"Named Maryland official, defender, rioter, printer, privateer, laborer, or witness", places:["Baltimore", "North Point", "Fort McHenry", "Chesapeake Bay"], events:["Baltimore riots", "city mobilization", "Battle for Baltimore"], unit:"Municipal, militia, newspaper, privateering, or labor network", allegiances:["Maryland civic and military networks—position varies"], identityConfidence:"Strong match", confidenceNote:"Name and Maryland context are supported in municipal, militia, newspaper, or narrative records; common names require local corroboration.", archiveReason:"Baltimore’s archive was produced by office, property, business, print, militia service, criminal accusation, injury, death, and commemoration. The reason a name survives is part of the historical evidence.", sourceRefs:["bca","msa-baltimore-records","nps-riots","nps-baltimore"], chapter:"baltimore-holds",
    names:`Alexander Contee Hanson|James M. Lingan|Henry Lee|John Thomson|Otho Sprigg|Edward Johnson|Jacob Wagner|William Gwynn|Hezekiah Niles|John S. Skinner|Francis Scott Key|William Beanes|Samuel Smith|John Stricker|George Armistead|Joshua Barney|Joseph Sterett|Aquilla Randall|Daniel Wells Jr.|Henry McComas|John Montgomery|James Biays|Thomas Kemp|Thomas Boyle|George Stiles|Luke Tiernan|William Patterson|Robert Gilmor Jr.|John Donnell|William Lorman|Henry Payson|Isaac McKim|William Greetham|John Hollins|Joseph Townsend|William Wilson|Charles Ridgely|John Eager Howard|Nicholas Brice|James Mosher|Benjamin Edes|Joseph Robinson|Philip Reed|Peter Parker|John B. Morris|John Merryman|John Merryman Jr.|George Decker|Benjamin Howard|Charles Sterett Ridgely|William H. Marriott|Joseph Hopper Nicholson|William Pinkney|Robert Goodloe Harper|Joseph H. Nicholson|Roger Brooke Taney|John Purviance|George Douglas|Thomas Tenant|John Berry|William McDonald|Richard Frisby|Samuel Etting|Bernard Eder|John H. Barney|William Frick|Elias Glenn|John Kilby|William Stewart|Thomas Sheppard|Joseph White|James Calhoun|Jeremiah Sullivan|John Hughes|William Cooke|Samuel Hollingsworth|Henry Didier|Charles Carroll of Carrollton|Charles Carroll of Homewood|Robert Oliver|David Winchester|William Winchester`
  },
];

const curatedRelationships: Record<string, { target: string; label: string }[]> = {
  "james-madison":[{target:"dolley-madison",label:"spouses and political household"},{target:"james-monroe",label:"president and secretary of state"},{target:"albert-gallatin",label:"administration and peace diplomacy"}],
  "mary-pickersgill":[{target:"grace-wisher",label:"indentured household labor"},{target:"rebecca-young",label:"mother, teacher, and flag-making trade"},{target:"caroline-pickersgill",label:"daughter and household work"}],
  "grace-wisher":[{target:"mary-pickersgill",label:"indentured household labor"},{target:"rebecca-young",label:"flag-making household network"},{target:"caroline-pickersgill",label:"shared household work"}],
  "alexander-contee-hanson":[{target:"ann-matilda-hanson",label:"spouses"},{target:"james-m-lingan",label:"defenders of the Federal Republican"},{target:"henry-lee",label:"defenders of the Federal Republican"},{target:"jacob-wagner",label:"newspaper business network"}],
  "andrew-jackson":[{target:"rachel-jackson",label:"spouses and political household"},{target:"john-coffee",label:"campaign command"},{target:"menawa",label:"opposing leaders at Horseshoe Bend"},{target:"william-mcintosh",label:"contingent wartime alliance"}],
  "tecumseh":[{target:"tenskwatawa",label:"brothers and coalition leadership"},{target:"isaac-brock",label:"strategic wartime alliance"},{target:"roundhead",label:"Indigenous coalition leadership"}],
  "tenskwatawa":[{target:"tecumseh",label:"brothers and coalition leadership"}],
  "francis-scott-key":[{target:"william-beanes",label:"truce mission and release"},{target:"george-armistead",label:"bombardment and flag memory"}],
  "samuel-smith":[{target:"john-stricker",label:"Baltimore defense command"},{target:"george-armistead",label:"city and harbor defense"},{target:"joshua-barney",label:"Chesapeake defense network"}],
  "oliver-hazard-perry":[{target:"william-henry-harrison",label:"lake victory and land campaign"},{target:"daniel-dobbins",label:"Lake Erie shipbuilding"}],
  "robert-ross":[{target:"alexander-cochrane",label:"Chesapeake expedition command"},{target:"john-stricker",label:"opposing commanders at North Point"}],
  "alexander-cochrane":[{target:"robert-ross",label:"Chesapeake expedition command"},{target:"george-cockburn",label:"Royal Navy operational command"}],
  "menawa":[{target:"andrew-jackson",label:"opposing leaders at Horseshoe Bend"},{target:"william-mcintosh",label:"divided Muscogee wartime politics"}],
  "jordan-noble":[{target:"andrew-jackson",label:"New Orleans defense coalition"}],
};

export const humanIndexRecords: HumanRecord[] = seeds.flatMap((seed) => seed.names.split("|").map((name) => ({
  slug: slugify(name),
  name,
  group: seed.group,
  role: seed.role,
  dates: undefined,
  places: seed.places,
  events: seed.events,
  unit: seed.unit,
  allegiances: seed.allegiances,
  identityConfidence: seed.identityConfidence,
  confidenceNote: seed.confidenceNote,
  archiveReason: seed.archiveReason,
  sourceRefs: seed.sourceRefs,
  chapter: seed.chapter,
  relationships: curatedRelationships[slugify(name)] ?? [],
  movements: seed.places.slice(0,3).map((place,index) => ({ date:index === 0 ? "Wartime record" : "Connected geography", place, note:index === 0 ? "The current index associates this person with this record group; verify the underlying item before making a finer claim." : "A research route, not proof that every person in the group traveled to every listed place." })),
  detail:"index" as const,
})));

export const humanRecordBySlug = Object.fromEntries(humanIndexRecords.map((record) => [record.slug, record]));

export const humanGroups = [...new Set(humanIndexRecords.map((record) => record.group))];
