export type SourceGroup = {
  id: string;
  title: string;
  description: string;
  sourceIds: string[];
};

export const sourceGroups: SourceGroup[] = [
  { id: "start", title: "Start Here", description: "The strongest broad entry points: a national research guide, public-history gateways, federal records, comparative Canadian interpretation, and two substantial campaign studies.", sourceIds: ["loc-guide", "nps-war", "nara-war", "cwm", "lac", "army-campaign-1812", "ontario-military-heritage", "hickey-forgotten-conflict"] },
  { id: "primary", title: "Primary Documents & Documentary Editions", description: "Specific statutes, messages, correspondence, treaties, printed accounts, and edited document collections used in the narrative. Read each document for its creator, purpose, and editorial history.", sourceIds: ["primary-embargo-act", "primary-madison-war-message", "primary-baltimore-narrative", "primary-hull-proclamation", "primary-brannan-letters", "primary-perry-dispatch", "primary-porter-journal", "primary-cochrane-proclamation", "primary-fort-jackson", "primary-ghent-dispatch", "primary-dolley-extract", "primary-key-broadside", "primary-jackson-address", "primary-rush-bagot", "founders-jefferson-duane", "asp-foreign-relations", "dudley-naval-war", "cruikshank-niagara", "kappler-treaties", "house-declaration", "loc-ghent", "avalon-ghent", "nara-impressment"] },
  { id: "manuscripts", title: "Manuscripts", description: "Catalogues and finding aids for personal papers and institutional records. Descriptions are often searchable even when the underlying documents are not digitized.", sourceIds: ["loc-manuscripts", "loc-finding-aids", "nysl-war", "bca"] },
  { id: "newspapers", title: "Historic Newspapers", description: "Searchable newspaper evidence for politics, casualty reports, commercial disruption, rumor, commemoration, and local reaction. OCR should always be checked against the page image.", sourceIds: ["loc-newspapers", "nps-riots", "bca"] },
  { id: "maps", title: "Maps", description: "Cartographic collections for campaign geography and changing landscapes. Historical maps are arguments and artifacts, not neutral basemaps.", sourceIds: ["loc-maps", "loc-guide", "nhhc-flotilla"] },
  { id: "images", title: "Images, Objects & Reuse", description: "Item-level catalogues for prints, drawings, and objects, plus institutional rights guidance. Dates, creators, retrospective imagery, and item-level rights language should be checked before reuse.", sourceIds: ["loc-pictures", "loc-fort-print", "smithsonian-flag", "whha-portrait", "whha-jennings", "loc-rights", "smithsonian-terms"] },
  { id: "us-archives", title: "U.S. Archives", description: "Federal military, naval, maritime, and legislative records, supported by national collection guides.", sourceIds: ["nara-war", "nara-impressment", "loc-guide", "house-declaration"] },
  { id: "canadian-archives", title: "Canadian Archives & Studies", description: "National and provincial routes into British North American military, militia, civilian, and government records, with specific studies of Queenston, John Norton, and Châteauguay.", sourceIds: ["lac", "archives-ontario", "canada-military-history", "ontario-military-heritage", "parks-queenston", "parks-john-norton", "parks-chateauguay"] },
  { id: "british", title: "British / Imperial Sources", description: "British government catalogues and perspectives on a conflict embedded in a much larger imperial and European war.", sourceIds: ["uk-discovery", "cwm", "lac"] },
  { id: "indigenous", title: "Indigenous Sources", description: "Resources centered on Indigenous objectives, coalitions, land, diplomacy, and the unequal peace. Institutional interpretation and federal treaty compilations are starting points, not substitutes for nation and tribal sources.", sourceIds: ["nps-indigenous", "nps-creek", "nps-horseshoe-participants", "nps-choctaw", "parks-john-norton", "primary-fort-jackson", "kappler-treaties", "sugden-tecumseh", "waselkov-conquering-spirit", "taylor-civil-war", "lac"] },
  { id: "black-history", title: "Black History / Slavery / Freedom Seeking", description: "Named lives, Black military service, British emancipation strategy, Spanish borderlands, and the choices made by enslaved and free people.", sourceIds: ["nps-freedom-1", "nps-freedom-2", "nps-colonial", "nps-tangier", "primary-cochrane-proclamation", "nps-charles-ball", "abt-frederick-hall", "parks-pierpoint", "parks-black-militia", "nps-prince-witten", "nps-new-orleans-black", "nps-jordan-noble", "primary-jackson-address", "midkiff-louisiana-battalions"] },
  { id: "women-civilians", title: "Women / Civilian Life", description: "Household labor, occupation, political violence, displacement, and the civilians whose wartime experiences survive unevenly in the record.", sourceIds: ["nps-living", "nps-women-chesapeake", "nps-elizabeth-sands", "nps-grace", "smithsonian-flag", "nps-riots", "primary-dolley-extract", "whha-portrait", "whha-jennings"] },
  { id: "naval", title: "Naval Sources", description: "The oceanic war, trade and blockade, privateering, lake fleets, coastal defense, archaeology, ships, sailors, and maritime identity.", sourceIds: ["nhhc", "dudley-naval-war", "nara-impressment", "nps-trade-commerce", "nps-privateers", "nps-lake-erie", "primary-perry-dispatch", "nps-freshwater", "malcomson-lords-lake", "skaggs-signal-victory", "nps-plattsburgh", "lac-british-records", "nhhc-flotilla"] },
  { id: "chesapeake", title: "Maryland / Chesapeake", description: "The project's home ground: civic violence, raids, slavery and freedom seeking, Washington, North Point, Fort McHenry, and Baltimore's defense system.", sourceIds: ["bca", "bca-directories", "msa-baltimore-records", "nps-riots", "msa-hanson", "riot-narrative", "primary-baltimore-narrative", "nps-tangier", "nhhc-flotilla", "sheads-chesapeake", "nps-baltimore-north-point", "nps-baltimore", "nps-north-point", "nps-bombardment", "nps-garrison-flag", "nps-grace", "abt-frederick-hall", "whha-war-finance"] },
  { id: "gulf", title: "Gulf / Creek / Spanish Borderlands", description: "Muscogee civil conflict, U.S. expansion, Spanish Florida, Black sanctuary, Choctaw participation, and the coalition at New Orleans.", sourceIds: ["nps-creek", "nps-horseshoe-participants", "primary-fort-jackson", "kappler-treaties", "waselkov-conquering-spirit", "nps-prince-witten", "nps-choctaw", "nps-new-orleans-black", "primary-jackson-address", "midkiff-louisiana-battalions", "nps-jean-lafitte", "nps-jordan-noble", "lafolklife"] },
  { id: "pacific", title: "Pacific", description: "The Essex cruise, British whaling, Valparaíso, Nuku Hiva, and Polynesian agency in a genuinely global war.", sourceIds: ["nhhc-pacific", "primary-porter-journal", "dudley-naval-war", "nhhc"] },
  { id: "prisoners", title: "Prisoners of War", description: "Collection guides for captivity, parole, prison records, and the American prisoners held in Britain. Catalogue records may require on-site research or reproduction orders.", sourceIds: ["nps-dartmoor", "loc-dartmoor", "nysl-war", "uk-discovery", "lac"] },
  { id: "diplomacy", title: "Diplomacy & Treaty", description: "Peace negotiations, the text of Ghent, restoration, borders, and the later choice to demilitarize the Great Lakes.", sourceIds: ["primary-ghent-dispatch", "asp-foreign-relations", "loc-ghent", "loc-ghent-digital", "avalon-ghent", "senate-ghent", "primary-rush-bagot", "state-rush-bagot", "lac"] },
  { id: "memory", title: "Memory / Commemoration", description: "How flags, songs, heroes, anniversaries, and national stories rearranged a complicated war after the fighting ended.", sourceIds: ["nps-legacies", "nps-creating-legacies", "nps-short-memory", "smithsonian-flag", "loc-fort-print", "cwm"] },
  { id: "scholarship", title: "Scholarly Works", description: "Specific interpretive books and studies used by the project, plus broader routes for continuing research. Follow disagreements across national, Indigenous, Black, gender, diplomatic, and military history.", sourceIds: ["hickey-forgotten-conflict", "stagg-madisons-war", "taylor-civil-war", "gilje-free-trade", "latimer-war-america", "benn-war-1812", "malcomson-lords-lake", "skaggs-signal-victory", "sugden-tecumseh", "waselkov-conquering-spirit", "sheads-chesapeake", "midkiff-louisiana-battalions", "worldcat-scholarship", "loc-guide", "nara-war"] },
];
