import type { Metadata } from "next";
import Link from "@/components/SafeLink";
import { notFound } from "next/navigation";
import { SourceList } from "@/components/SourceList";
import { events } from "@/lib/content";

export function generateStaticParams() { return events.map((event) => ({ slug: event.id })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const event = events.find((item) => item.id === slug); return event ? { title: event.title, description: event.summary } : {}; }
export default async function EventPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const event = events.find((item) => item.id === slug); if (!event) notFound(); return <main id="main" className="record-page"><header className="record-hero"><div><p className="section-kicker">Event record · {event.type}</p><p className="record-eyebrow">{event.place} · {event.theater}</p><h1>{event.title}</h1><p className="record-dates">{event.date}</p></div></header><div className="record-body"><section className="record-summary"><p>{event.summary}</p><div className="event-detail-grid"><div><h2>Participants</h2><ul>{event.participants.map((participant) => <li key={participant}>{participant}</li>)}</ul></div><div><h2>Outcome</h2><p>{event.outcome}</p></div><div><h2>Why it matters</h2><p>{event.significance}</p></div><div><h2>Location evidence</h2><p>{event.latitude.toFixed(3)}, {event.longitude.toFixed(3)} · {event.coordinatePrecision} precision</p><p>Coordinates locate the named site, city, or broad region; they do not reconstruct unit movements.</p></div></div><h2>Where it sits in the story</h2><p>This record belongs to a connected military, political, and human sequence. The chapter supplies causes, consequences, competing perspectives, and the limits of the surviving evidence.</p></section><div className="record-actions"><Link className="primary-action" href={`/story/${event.chapter}`}>Read the connected story <span>→</span></Link><Link href={`/map?event=${event.id}`}>See the map</Link><Link href="/events">Back to events</Link></div><SourceList ids={event.sourceRefs} heading="Evidence behind this event" /></div></main>; }
