import type { Metadata } from "next";
import Link from "next/link";
import { SourceList } from "@/components/SourceList";

export const metadata: Metadata = { title: "History in Your Own Backyard", description: "A mobile field guide to the War of 1812 in Maryland—from Chesapeake raids and Bladensburg to North Point and Fort McHenry." };

const stops = [
  ["Havre de Grace", "3 May 1813", "A British raid burned much of the town and showed how quickly naval power could reach civilian streets.", "/places/havre-de-grace"],
  ["Bladensburg", "24 August 1814", "The American defense collapsed, opening the road to Washington; Barney’s sailors and marines made the hardest stand.", "/places/bladensburg"],
  ["North Point", "12 September 1814", "Stricker’s militia delayed the British advance and withdrew into Baltimore’s prepared defenses.", "/places/north-point"],
  ["Fort McHenry", "13–14 September 1814", "The fort and harbor batteries survived a night of bombs, rockets, rain, and uncertainty.", "/places/fort-mchenry"],
] as const;

export default function BackyardPage() {
  return (
    <main id="main" className="backyard-page">
      <header className="backyard-hero"><div><p className="section-kicker">A mobile Maryland field guide</p><h1>History in Your Own Backyard</h1><p>You do not have to travel to a remote battlefield. In Maryland, the roads, rivers, towns, harbor approaches, and neighborhoods around you were part of the campaign.</p><div className="backyard-actions"><Link className="primary-action" href="/map">Open the campaign map <span>→</span></Link><Link href="/maryland">Explore all Maryland stories</Link></div></div></header>

      <section className="backyard-stops" aria-labelledby="stops-heading"><div className="section-heading"><p className="section-kicker">Four places to begin</p><h2 id="stops-heading">Follow the campaign on the ground</h2></div><div>{stops.map(([name, date, copy, href], index) => <Link href={href} key={name}><span className="stop-number">{String(index + 1).padStart(2, "0")}</span><time>{date}</time><h3>{name}</h3><p>{copy}</p><b>Open place record →</b></Link>)}</div></section>

      <article className="backyard-story">
        <header><p className="section-kicker">The Battle of Baltimore in five minutes</p><h2>A city waits behind earthworks</h2></header>
        <section><span>01</span><div><h3>The Chesapeake road</h3><p>The British did not suddenly appear outside Baltimore in September 1814. For more than a year, Royal Navy ships had blockaded the Chesapeake, raided its shores, gathered intelligence, and demonstrated how exposed the bay’s towns and plantations were. Havre de Grace burned in May 1813. St. Michaels resisted attack. Joshua Barney’s Chesapeake Flotilla tried to make the shallow rivers and creeks dangerous for larger British vessels.</p><p>The campaign created very different possibilities for people living along the water. Merchants saw trade contract. Families watched for sails. Enslaved people weighed the terrible risks of attempting to reach British ships, where an imperial military policy offered a path out of American slavery. By 1814, the bay was not merely an approach to the war. It was one of the war’s central landscapes.</p></div></section>
        <section><span>02</span><div><h3>Washington burns; Baltimore prepares</h3><p>British troops landed at Benedict on the Patuxent in August 1814, defeated a disordered American defense at Bladensburg, and burned public buildings in Washington. Baltimore had no reason to assume it would be spared. It was a major port, a center of privateering, and a city British officers regarded as a nest of hostile commerce.</p><p>Major General Samuel Smith oversaw defenses that joined geography to civic labor: earthworks east of the city, militia and regular troops, artillery, harbor obstructions, Fort McHenry, supporting batteries, supply systems, and thousands of workers. Free and enslaved Black laborers helped build those defenses. Women, tradespeople, businesses, sailors, and officials sustained them. The city’s apparent unity had been made under pressure; only two years earlier, partisan violence had ended with James M. Lingan murdered in the city jail.</p></div></section>
        <section><span>03</span><div><h3>North Point buys time</h3><p>British troops landed at North Point on September 12. Major General Robert Ross rode forward and was mortally wounded in a skirmish. Colonel Arthur Brooke took command and continued toward Brigadier General John Stricker’s Maryland militia.</p><p>Stricker did not need to destroy the British army. He needed to delay it, preserve enough of his force to strengthen Baltimore’s main line, and make Brooke confront a prepared city rather than pursue another collapse like Bladensburg. After hard fighting and pressure on his flank, Stricker withdrew in order. The British held the field, but the American defense had done strategically useful work.</p></div></section>
        <section><span>04</span><div><h3>The night at the harbor</h3><p>The naval bombardment began on September 13. British bomb vessels and a rocket ship fired from beyond the effective range of most American guns. Rain and low cloud obscured the scene. Fort McHenry’s defenders could endure the fire, but they could not know whether Brooke’s army was breaking through on land.</p><p>During the night, British boats moved toward another branch of the harbor, hoping to threaten the defenses from a new direction. American fire helped turn them back. The naval force could not open the water route; Brooke faced formidable earthworks on land. The two parts of the British operation had failed to create an opening for each other.</p></div></section>
        <section><span>05</span><div><h3>The flag becomes evidence</h3><p>Mary Pickersgill’s household made two flags for Fort McHenry: a smaller storm flag and the enormous garrison flag now held by the Smithsonian. Grace Wisher, a young African American indentured servant, was part of that skilled household labor. The object’s history is therefore also a history of work, race, gender, and power in wartime Baltimore.</p><p>Francis Scott Key watched from a truce vessel after helping secure the release of Dr. William Beanes. At morning, the flag told him the fort had not surrendered. His poem became a song and, much later, a national anthem. The immediate military result was more concrete: Baltimore remained beyond British control.</p></div></section>
      </article>

      <aside className="field-note"><p className="section-kicker">When you visit</p><h2>Read the landscape, not just the monument</h2><p>Ask what a defender could see, how troops and supplies moved, where water controlled access, and whose labor created the position. Then ask who is easiest to commemorate—and who is easiest to lose.</p><div><Link href="/story/baltimore-holds">Read the complete Baltimore chapter →</Link><Link href="/objects/star-spangled-banner">Examine the garrison flag →</Link><Link href="/people/grace-wisher">Meet Grace Wisher →</Link></div></aside>
      <div className="backyard-sources"><SourceList ids={["nps-living", "nps-freedom-1", "nhhc-flotilla", "nps-baltimore", "nps-north-point", "nps-bombardment", "nps-grace", "smithsonian-flag"]} heading="Sources for this field guide" /></div>
    </main>
  );
}

