import type { Metadata } from "next";
import Link from "@/components/SafeLink";
import { BaltimoreExhibition } from "@/components/BaltimoreExhibition";
import { SourceList } from "@/components/SourceList";

export const metadata: Metadata = { title: "Baltimore, 1812–1814", description: "How one city murdered a Revolutionary general, built a fortress, stopped an empire, and remembered only part of the story." };

const people = [
  ["Alexander Contee Hanson", "The antiwar editor refused to let destruction of his press settle whether dissent could be printed.", "/people/alexander-contee-hanson"],
  ["James M. Lingan", "A Revolutionary officer and former prisoner of war, murdered while supposedly protected by the city.", "/people/james-m-lingan"],
  ["Henry “Light-Horse Harry” Lee", "A celebrated Revolutionary commander, savagely beaten and never fully recovered.", "/people/henry-lee"],
  ["Samuel Smith", "Merchant, politician, veteran, and militia general who coordinated Baltimore’s layered defense.", "/people/samuel-smith"],
  ["John Stricker", "His militia delayed the British at North Point and withdrew into the city’s main line.", "/people/john-stricker"],
  ["Grace Wisher", "Her skilled labor in the Pickersgill household belongs inside the history of the famous flag.", "/people/grace-wisher"],
];

export default function BaltimorePage() { return <main id="main" className="baltimore-exhibition">
  <header className="baltimore-exhibition-hero"><div><p className="section-kicker">A city between memory and evidence</p><h1><span>Baltimore</span><b>1812—1814</b></h1><p>How a city murdered a Revolutionary general, built a fortress, stopped an empire—and remembered only part of the story.</p><div><a className="primary-action" href="#city-layer-title">Enter the exhibition <span>↓</span></a><Link href="/maryland">Maryland gateway →</Link></div></div></header>
  <section className="baltimore-thesis"><p className="section-kicker">The argument</p><h2>Patriotism did not replace violence.<br />It reorganized the city’s memory.</h2><div><p>In 1812, Baltimore’s political machinery failed at the most basic civic task. A crowd destroyed an opposition press. Armed Federalists then defended a Charles Street house. Officials promised protection, moved the defenders into custody, and failed to keep a mob from entering the jail. James M. Lingan was murdered. Henry Lee, Alexander Contee Hanson, and others were tortured and gravely injured.</p><p>In 1814, Baltimore mobilized with extraordinary effectiveness. Money, intelligence, industry, militia, sailors, artillery, privateering networks, harbor defenses, earthworks, and thousands of laborers formed one defensive system. The city did not become simple or equal. It became capable of directing unequal civic resources toward an external enemy.</p><p>Later commemoration turned the defense into Baltimore’s public identity. The Battle Monument entered the city seal. The flag became a national relic. The riots never received comparable civic weight. Holding the two years together does not diminish the defense. It reveals what—and whom—a city chooses to remember.</p></div></section>
  <BaltimoreExhibition />
  <section className="baltimore-comparison"><div className="comparison-year"><span>1812</span><h2>War with itself</h2><dl><div><dt>Object under attack</dt><dd>An opposition newspaper and its defenders</dd></div><div><dt>Civic instrument</dt><dd>The crowd, partisan rhetoric, municipal neglect</dd></div><div><dt>Military memory invoked</dt><dd>Revolutionary veterans labeled traitors</dd></div><div><dt>Institutional outcome</dt><dd>Custody becomes exposure to murder</dd></div><div><dt>Public afterlife</dt><dd>Condemned, minimized, locally peripheral</dd></div></dl></div><div className="comparison-axis"><span>Two summers</span><b>27 months</b><span>One city</span></div><div className="comparison-year"><span>1814</span><h2>War with an empire</h2><dl><div><dt>Object under attack</dt><dd>A port, privateering center, and defended city</dd></div><div><dt>Civic instrument</dt><dd>Militia, labor, money, industry, intelligence</dd></div><div><dt>Military memory invoked</dt><dd>The Revolution as shared inheritance</dd></div><div><dt>Institutional outcome</dt><dd>Land and water approaches remain closed</dd></div><div><dt>Public afterlife</dt><dd>Monument, anthem, seal, annual celebration</dd></div></dl></div></section>
  <section className="baltimore-people"><header><p className="section-kicker">No city acts by itself</p><h2>Six lives across the bookend</h2></header><div>{people.map(([name, copy, href], index) => <Link href={href} key={name}><span>{String(index + 1).padStart(2,"0")}</span><h3>{name}</h3><p>{copy}</p><b>Open record →</b></Link>)}</div></section>
  <section className="baltimore-memory"><div><p className="section-kicker">History / Memory / Evidence</p><h2>The monument and the missing monument</h2></div><div><p>Baltimore began its Battle Monument in 1815. It names the military dead of North Point and Fort McHenry and eventually became the principal emblem on the city seal. The successful defense was transformed into a durable civic origin story almost immediately.</p><p>Lingan’s murder produced outrage, legislative condemnation, partisan pamphlets, testimony, and funeral commemoration. It did not produce a comparable organizing landmark in Baltimore. The asymmetry is evidence. Cities do not merely inherit memory; they allocate prestige, space, repetition, and official imagery.</p><blockquote>What would Baltimore’s identity look like if the jail stood beside the fort in civic memory?</blockquote><p>The question is not an accusation against commemoration of 1814. It is an invitation to recognize that the city’s finest wartime achievement and its most shameful wartime failure belong to the same public history.</p></div></section>
  <section className="baltimore-reading"><div><p className="section-kicker">Continue through the evidence</p><h2>Two chapters.<br />One civic history.</h2></div><div><Link href="/story/baltimore-at-war-with-itself"><span>1812</span><strong>Baltimore I: A City at War With Itself</strong><b>Read chapter →</b></Link><Link href="/story/baltimore-holds"><span>1814</span><strong>Baltimore II: A City at War With an Empire</strong><b>Read chapter →</b></Link><Link href="/backyard"><span>Field guide</span><strong>Read the surviving landscape</strong><b>Go outside →</b></Link></div></section>
  <div className="baltimore-sources"><SourceList ids={["house-declaration","nps-riots","msa-hanson","riot-narrative","bca","nps-baltimore-north-point","nps-baltimore","nps-north-point","nps-bombardment","nps-privateers","nps-grace","smithsonian-flag"]} heading="Evidence for this exhibition" /></div>
</main>; }
